<?php
$client=ins_record($u,$a,(int)$_GET['id']);if($client['kind']!=='clients')throw new DomainException('Client not found.');$c=$client['data'];$cid=(int)$client['id'];
function hub_return(int $cid):void{ihidden('return_client',$cid);}
function hub_form(array $u,array $a,int $cid,string $kind,?array $record=null):void{
    try{ins_allow($u,$a,$kind,'edit');}catch(DomainException){echo '<p class="muted">Read-only access.</p>';return;}$d=$record['data']??[];
    echo '<form method="post" class="form-grid">';iform('save');hub_return($cid);ihidden('kind',$kind);ihidden('id',$record['id']??0);ihidden('version',$record['version']??0);ihidden('client_id',$cid);ihidden('assigned_id',$record['assigned_id']??$u['id']);
    foreach(ins_fields($kind) as $key=>$type){$v=$d[$key]??'';if($type==='money')ifield($key,'number',$v!==''?$v/100:'');elseif($type==='frequency'){$opts=['once','weekly','monthly','quarterly','half-yearly','yearly'];iselect($key,array_combine($opts,$opts),$v?:'once');}elseif($type==='category')iselect($key,array_combine($a['settings']['categories'],$a['settings']['categories']),$v);elseif(str_starts_with($type,'select:')){$opts=explode(',',substr($type,7));iselect($key,array_combine($opts,$opts),$v?:$opts[0]);}else ifield($key,$type,$v);}
    echo '<button>Save '.ie($kind==='clients'?'client':'record').'</button></form>';
}
?>
<a class="back-link" href="<?=ie(iu('clients'))?>">← All clients</a>
<section class="panel client-heading"><div class="section-head"><div><span class="eyebrow">CLIENT OVERVIEW</span><h2><?=ie($c['name'])?></h2><p><?=ie($c['city']??'')?> · <?=ie($c['email']?:'No email recorded')?> · <?=ie($c['phone']?:'No phone recorded')?></p></div><span class="badge"><?=$client['archived']?'Archived':'Client'?></span></div>
<div class="form-grid"><div><h3>Contact details</h3><p><?=nl2br(ie($c['address']?:'No address recorded'))?> <?=ie($c['pincode'])?></p><p>Date of birth: <?=ie($c['dob']?:'Not recorded')?></p><p>Source: <?=ie($c['source']?:'Not recorded')?> · Tags: <?=ie($c['tags']?:'None')?></p></div><div><h3>Family & notes</h3><p><?=nl2br(ie($c['family']?:'No family details yet'))?></p><p><?=nl2br(ie($c['notes']))?></p></div></div>
<div class="actions"><?php if($c['phone']):?><a class="button secondary" href="tel:<?=ie(preg_replace('/[^+0-9]/','',$c['phone']))?>">Call</a><?php endif ?><?php if($c['email']&&in_array($c['consent'],['email','both'],true)):?><a class="button secondary" href="mailto:<?=ie($c['email'])?>">Compose email</a><?php endif ?></div>
<details class="compact-edit"><summary>Edit client details</summary><?php hub_form($u,$a,$cid,'clients',$client);?></details></section>
<?php
$sections=['policies'=>'Policies & coverage','investments'=>'Investments','leads'=>'Follow-ups','claims'=>'Claims','commissions'=>'Commissions'];
foreach($sections as $kind=>$label):if(!in_array($kind,$a['settings']['modules'],true))continue;
try{$rows=array_values(array_filter(ins_records($u,$a,$kind),fn($r)=>(int)$r['client_id']===$cid));}catch(DomainException){continue;}
?>
<section class="panel"><div class="section-head"><h2><?=ie($label)?> <span class="badge"><?=count($rows)?></span></h2></div>
<?php foreach($rows as $r):$d=$r['data'];?><article class="hub-record"><div class="section-head"><div><h3><?=ie($d['name'])?></h3><p><?=ie($d['provider']??$d['stage']??'')?> <span class="badge"><?=ie($d['status']??'')?></span></p></div></div>
<?php if($kind==='policies'):?><div class="coverage-grid"><div><small>Policy number</small><strong><?=ie($d['policy_number']?:'Not recorded')?></strong></div><div><small>Coverage period</small><strong><?=ie($d['start']?:'—')?> → <?=ie($d['expiry']?:'Open-ended')?></strong></div><div><small>Premium</small><strong><?=im((int)$d['premium'])?> · <?=ie($d['frequency'])?></strong></div><div><small>Next premium due</small><strong><?=ie($d['next_due']?:'Not scheduled')?></strong></div></div>
<details class="compact-edit"><summary>Renew / update coverage dates</summary><p>Record the next confirmed coverage period. Previous dates and premium stay in History. This does not record a payment.</p><form method="post" class="form-grid"><?php iform('renew_period');hub_return($cid);ihidden('id',$r['id']);ihidden('version',$r['version']);$nextStart=$d['expiry']?(new DateTimeImmutable($d['expiry']))->modify('+1 day')->format('Y-m-d'):'';ifield('start','date',$nextStart,'New coverage start');ifield('expiry','date','','New coverage expiry');ifield('premium','number',$d['premium']/100,'Renewal premium');ifield('next_due','date','','Next premium due (separate from expiry)');?><button>Confirm renewal</button></form></details>
<details><summary>History · previous coverage periods</summary><div class="table-wrap"><table><tr><th>Period</th><th>Premium</th><th>Recorded</th></tr><tr><td><?=ie($d['start'])?> → <?=ie($d['expiry'])?> · Current</td><td><?=im((int)$d['premium'])?></td><td><?=ie(substr($r['updated_at'],0,10))?></td></tr><?php $seen=[$d['start'].'|'.$d['expiry'].'|'.$d['premium']=>true];foreach(ins_query('SELECT * FROM record_revisions WHERE agency_id=? AND record_id=? ORDER BY id DESC',[$a['id'],$r['id']])->fetchAll() as $rev):$old=json_decode($rev['data'],true);$key=($old['start']??'').'|'.($old['expiry']??'').'|'.($old['premium']??0);if(isset($seen[$key]))continue;$seen[$key]=true;?><tr><td><?=ie($old['start']??'')?> → <?=ie($old['expiry']??'')?></td><td><?=im((int)($old['premium']??0))?></td><td><?=ie(substr($rev['created_at'],0,10))?></td></tr><?php endforeach ?></table></div></details>
<?php else:?><p><?=ie($d['next_action']??$d['scheme']??$d['reference']??'')?></p><p>Next date: <?=ie($d['next_due']??'Not scheduled')?></p><?php endif ?>
<details><summary>View full details</summary><dl class="record-details"><?php foreach(ins_fields($kind) as $key=>$type):$v=$d[$key]??'';if($v==='')continue;?><dt><?=ie(ucwords(str_replace('_',' ',$key)))?></dt><dd><?=nl2br(ie($type==='money'?im((int)$v):$v))?></dd><?php endforeach ?></dl></details>
<details class="compact-edit"><summary>Edit / manage record</summary><?php hub_form($u,$a,$cid,$kind,$r);?><form method="post" class="archive-form"><?php iform('archive');hub_return($cid);ihidden('id',$r['id']);?><button class="secondary">Archive record</button></form><small>Archive hides this item without permanently deleting it.</small></details></article><?php endforeach ?>
<?php if(!$rows):?><p class="muted">No <?=ie(strtolower($label))?> recorded for this client.</p><?php endif ?>
<details><summary>+ Add <?=ie($kind==='policies'?'policy':($kind==='leads'?'follow-up':rtrim($kind,'s')))?></summary><?php hub_form($u,$a,$cid,$kind);?></details>
</section><?php endforeach ?>
<?php if(in_array('dues',$a['settings']['modules'],true)):ins_allow($u,$a,'dues');?><section class="panel"><h2>Payments & client statement</h2><div class="table-wrap"><table><tr><th>Due date</th><th>Type</th><th>Amount</th><th>Received</th><th>Balance</th></tr><?php foreach(ins_query("SELECT * FROM events WHERE agency_id=? AND client_id=? AND type IN ('premium','contribution') AND status<>'cancelled' ORDER BY due DESC",[$a['id'],$cid])->fetchAll() as $e):try{ins_event($u,$a,(int)$e['id']);}catch(DomainException){continue;}?><tr><td><?=ie($e['due'])?></td><td><?=ie($e['type'])?></td><td><?=im((int)$e['amount'])?></td><td><?=im((int)$e['received'])?></td><td><?=im((int)$e['amount']-(int)$e['received'])?><?php if($e['status']==='open'):?><details><summary>Record payment</summary><form method="post"><?php iform('payment');hub_return($cid);ihidden('event_id',$e['id']);ifield('amount','number',($e['amount']-$e['received'])/100);ifield('paid_at','date',date('Y-m-d'));ifield('reference');?><button>Save manual payment</button></form></details><?php endif ?></td></tr><?php endforeach ?></table></div></section><?php endif ?>
<?php if(in_array('documents',$a['settings']['modules'],true)):ins_allow($u,$a,'documents');?><section class="panel"><h2>Documents</h2><?php foreach(ins_records($u,$a,'documents') as $doc):if((int)$doc['client_id']!==$cid)continue;?><p><a href="<?=ie(iu('documents',['download'=>$doc['id']]))?>"><?=ie($doc['data']['name'])?> · Download</a></p><?php endforeach ?><details><summary>+ Add document</summary><form method="post" enctype="multipart/form-data" class="form-grid"><?php iform('upload');hub_return($cid);ihidden('client_id',$cid);ifield('label');?><label>PDF / JPEG / PNG · max 5 MB<input type="file" name="document" accept="application/pdf,image/jpeg,image/png" required></label><button>Upload privately</button></form></details></section><?php endif ?>
<details class="panel"><summary>Archived records</summary><?php foreach(array_keys($sections) as $kind){try{foreach(ins_records($u,$a,$kind,true) as $r){if((int)$r['client_id']!==$cid)continue;echo '<form method="post"><p>'.ie($r['data']['name']).'</p>';iform('archive');hub_return($cid);ihidden('id',$r['id']);echo '<button class="secondary">Restore</button></form>';}}catch(DomainException){}}?></details>
