<?php
$c=$selected['data'];$profileTab=(string)($_GET['tab']??'overview');
$tabs=['overview'=>'Overview','family'=>'Family','policies'=>'Policies','investments'=>'Investments','payments'=>'Payments','documents'=>'Documents','followups'=>'Follow-ups','activity'=>'Activity'];
?>
<section class="panel"><div class="section-head"><div><span class="eyebrow">CLIENT PROFILE</span><h2><?=ie($c['name'])?></h2><p><?=ie($c['city']??'')?> · <?=ie($c['email']??'')?></p></div><div class="actions"><a class="button secondary" href="<?=ie(iu('clients',['id'=>$selected['id'],'edit'=>1]))?>">Edit client</a><?php if(!empty($c['phone'])):?><a class="button secondary" href="tel:<?=ie(preg_replace('/[^+0-9]/','',$c['phone']))?>">Call</a><?php endif ?></div></div>
<nav class="profile-tabs"><?php foreach($tabs as $key=>$label):?><a class="<?=$profileTab===$key?'active':''?>" href="<?=ie(iu('clients',['id'=>$selected['id'],'tab'=>$key]))?>"><?=ie($label)?></a><?php endforeach ?></nav>
<?php if($profileTab==='overview'):?><div class="form-grid"><div><h3>Contact & address</h3><p><?=ie($c['phone']?:'No phone recorded')?></p><p><?=nl2br(ie($c['address']??''))?> <?=ie($c['pincode']??'')?></p><p>Date of birth: <?=ie($c['dob']?:'Not recorded')?></p><p>Consent: <?=ie($c['consent'])?></p></div><div><h3>Notes</h3><p><?=nl2br(ie($c['notes']))?></p><p>Tags: <?=ie($c['tags']??'')?></p><div class="actions"><?php if(in_array($c['consent'],['email','both'],true)&&$c['email']):?><a class="button secondary" href="mailto:<?=ie($c['email'])?>">Compose email</a><?php endif ?><?php if(in_array($c['consent'],['whatsapp','both'],true)&&preg_match('/^\+?[1-9]\d{7,14}$/',preg_replace('/[\s()-]/','',$c['phone']))):?><a class="button secondary" href="https://wa.me/<?=ie(preg_replace('/\D/','',$c['phone']))?>?text=<?=rawurlencode('Hello '.$c['name'].', ')?>" target="_blank" rel="noopener">Compose WhatsApp</a><?php endif ?></div><small>Opening a composer is not confirmation of delivery.</small></div></div>
<?php elseif($profileTab==='family'):?><h3>Family members & relationships</h3><p><?=nl2br(ie($c['family']?:'No family details recorded. Use Edit client to add them.'))?></p>
<?php elseif(in_array($profileTab,['policies','investments','documents','followups'],true)):$kind=$profileTab==='followups'?'leads':$profileTab;$linked=array_values(array_filter(ins_records($u,$a,$kind),fn($r)=>(int)$r['client_id']===(int)$selected['id']));?><p><a class="button" href="<?=ie(iu($kind,['new'=>1,'client_id'=>$selected['id']]))?>">Add <?=ie($profileTab==='followups'?'follow-up':rtrim($kind,'s'))?></a></p><?php if($kind==='documents'){foreach($linked as $doc)echo '<p><a href="'.ie(iu('documents',['download'=>$doc['id']])).'">'.ie($doc['data']['name']).'</a></p>';if(!$linked)echo '<p>No documents yet.</p>';}else ilist($linked,$kind);?>
<?php elseif($profileTab==='payments'):ins_allow($u,$a,'dues');?><div class="table-wrap"><table><tr><th>Date</th><th>Event</th><th>Received</th><th>Reference</th></tr><?php foreach(ins_query('SELECT p.*,e.record_id,e.type FROM payments p JOIN events e ON e.id=p.event_id WHERE p.agency_id=? AND e.client_id=? ORDER BY p.id DESC',[$a['id'],$selected['id']])->fetchAll() as $pay){try{ins_record($u,$a,(int)$pay['record_id']);?><tr><td><?=ie($pay['paid_at'])?></td><td><?=ie($pay['type'])?></td><td><?=im((int)$pay['amount'])?></td><td><?=ie($pay['reference'])?> · manually recorded</td></tr><?php }catch(DomainException){}}?></table></div>
<?php elseif($profileTab==='activity'):?><h3>Record history</h3><?php foreach(ins_query('SELECT version,created_at FROM record_revisions WHERE agency_id=? AND record_id=? ORDER BY id DESC',[$a['id'],$selected['id']])->fetchAll() as $rev):?><p>Version <?=ie($rev['version'])?> preserved · <?=ie($rev['created_at'])?></p><?php endforeach ?><p>Created <?=ie($selected['created_at'])?> · last updated <?=ie($selected['updated_at'])?></p><?php endif ?></section>
