<?php
function iform(string $action): void {echo '<input type="hidden" name="csrf" value="'.ie($_SESSION['ins_csrf']).'"><input type="hidden" name="action" value="'.ie($action).'">';}
function ihidden(string $name,mixed $value): void {echo '<input type="hidden" name="'.ie($name).'" value="'.ie($value).'">';}
function ifield(string $name,string $type='text',mixed $value='',?string $label=null): void {echo '<label>'.ie($label??ucwords(str_replace('_',' ',$name)));if($type==='textarea')echo '<textarea name="'.ie($name).'" rows="3">'.ie($value).'</textarea>';else echo '<input name="'.ie($name).'" type="'.ie($type).'" value="'.ie($value).'"'.($type==='number'?' min="0" step="0.01"':'').'>';echo '</label>';}
function iselect(string $name,array $options,mixed $selected='',?string $label=null): void {echo '<label>'.ie($label??ucwords(str_replace('_',' ',$name))).'<select name="'.ie($name).'">';foreach($options as $v=>$text)echo '<option value="'.ie($v).'"'.((string)$v===(string)$selected?' selected':'').'>'.ie($text).'</option>';echo '</select></label>';}
function ioptions(array $rows): array {$out=[''=>'Choose…'];foreach($rows as $r)$out[$r['id']]=$r['data']['name'];return $out;}
function icontact(array $d): void {
    $phone=preg_replace('/[^+0-9]/','',$d['phone']??'');$wa=preg_replace('/\D/','',$phone);
    if(preg_match('/^[6-9]\d{9}$/',$wa))$wa='91'.$wa;
    if($phone)echo '<a class="button secondary" href="tel:'.ie($phone).'">Call</a>';else echo '<button class="secondary" disabled title="Add a phone number">Call</button>';
    if(preg_match('/^[1-9]\d{7,14}$/',$wa)&&in_array($d['consent']??'none',['whatsapp','both'],true))echo '<a class="button secondary" target="_blank" rel="noopener" href="https://wa.me/'.ie($wa).'">WhatsApp</a>';else echo '<button class="secondary" disabled title="Add an international mobile number and WhatsApp consent">WhatsApp</button>';
}
function ilist(array $rows,string $kind): void { ?>
<div class="record-cards"><?php foreach($rows as $r):?><article class="record-card"><h3><?=ie($r['data']['name'])?></h3><p><?=ie($r['data']['provider']??$r['data']['email']??'')?></p><div class="actions"><a class="button secondary" href="<?=ie(iu($kind,['id'=>$r['id']]))?>"><?=$kind==='clients'?'View client':'Open record'?></a><?php if($kind==='clients')icontact($r['data']);?></div></article><?php endforeach ?></div>
<div class="table-wrap record-table"><table><thead><tr><th>Name</th><th>Details</th><th>Updated</th><th>Actions</th></tr></thead><tbody>
<?php foreach($rows as $r): $d=$r['data']; ?><tr><td><a href="<?=ie(iu($kind,['id'=>$r['id']]))?>"><?=ie($d['name'])?></a></td><td><?=ie($d['provider']??$d['email']??$d['stage']??'')?> <span class="badge"><?=ie($d['status']??$d['label']??'')?></span></td><td><?=ie(substr($r['updated_at'],0,10))?></td><td><div class="actions"><a class="button secondary" href="<?=ie(iu($kind,['id'=>$r['id']]))?>"><?=$kind==='clients'?'View client':'Open'?></a><?php if($kind==='clients')icontact($d);?></div></td></tr><?php endforeach ?>
<?php if(!$rows): ?><tr><td colspan="4">No records yet. Add your first record to get started.</td></tr><?php endif ?></tbody></table></div><?php }
$nav=['dashboard'=>'Dashboard','clients'=>'Clients','dues'=>'Due reminders','plans'=>'Plans & Costing','calculators'=>'Calculators','settings'=>'Settings'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Insurance · RAY</title><link rel="stylesheet" href="/insurance/assets/app.css"><link rel="stylesheet" href="/insurance/assets/meeting.css"><link rel="stylesheet" href="/insurance/assets/client-hub.css"><link rel="stylesheet" href="/insurance/assets/compact-header.css?v=20261008"><script src="/insurance/assets/app.js?v=20261008-header" defer></script></head><body>
<?php if(!$u): ?><main class="login"><div class="brand">RAY <span>Insurance</span></div><h1>Welcome back</h1><p>Insurance & investment agency workspace</p><?php if($error): ?><p class="alert error" role="alert"><?=ie($error)?></p><?php endif ?><?php if($notice): ?><p class="alert"><?=ie($notice)?></p><?php endif ?>
<form method="post"><?php iform('login');ifield('email','email');ifield('password','password');?><button>Sign in</button></form><details><summary>Reset password</summary><p>Ask your server administrator for a one-use reset token. No email provider is connected yet.</p><form method="post"><?php iform('reset');ifield('token');ifield('password','password','','New password (12+ characters)');?><button>Reset password</button></form></details><p class="muted">First run? Follow insurance/README.md to create your local administrator. No default production password.</p></main>
<?php else: ?>
<aside id="sidebar"><a class="brand" href="<?=ie(iu())?>">RAY <span>Insurance</span></a><p class="agency"><?=ie($a['name']??'Techdecodes · Platform')?></p><nav><?php foreach($nav as $key=>$label):if(!$a&&$key!=='dashboard')continue;if($a&&!in_array($key,['dashboard','settings'])&&!in_array($key,$a['settings']['modules'],true))continue;if($u['role']==='staff'&&!in_array('view',$u['permissions'][$key]??[],true)&&$key!=='dashboard')continue;?><a class="<?=$page===$key?'active':''?>" href="<?=ie(iu($key))?>"><?=ie($label)?></a><?php endforeach ?></nav><a class="all-businesses" href="/">← All businesses</a><form method="post"><?php iform('logout');?><button class="secondary">Sign out</button></form></aside>
<main class="workspace"><header><div><span class="eyebrow"><?=ie($a?'AGENCY WORKSPACE':'PLATFORM ADMIN')?></span><h1><?=ie($nav[$page]??'Insurance')?></h1></div><div class="header-actions"><button class="secondary" id="menu" aria-controls="sidebar" aria-expanded="false">Menu</button><a class="button secondary" id="refresh" href="?<?=ie(http_build_query(array_merge($_GET,['_refresh'=>(string)microtime(true),'__ray_action'=>'refresh'])))?>" aria-label="Refresh current page">Refresh</a><button class="secondary" id="fullscreen">Full screen</button><button class="secondary" id="theme" aria-label="Switch light and dark theme">Theme</button></div></header>
<?php if($a&&$a['demo']):?><p class="alert">DEMO AGENCY — isolated sample workspace. Do not enter real client information.</p><?php endif ?>
<?php if($u['role']==='platform'&&$a):?><form method="post" class="alert"><?php iform('exit_support');?>Read-only support session. Access is logged. <button class="secondary">Exit agency</button></form><?php endif ?>
<?php if($error):?><p class="alert error" role="alert"><?=ie($error)?></p><?php endif ?><?php if($notice):?><p class="alert" role="status"><?=ie($notice)?></p><?php endif ?>
<?php try { if(!$a): if($u['role']!=='platform')throw new DomainException('Your agency is unavailable. Contact the platform administrator.'); ?>
<section class="panel"><h2>Agency accounts</h2><p>Operational information only. Client access requires an agency administrator’s explicit, time-limited support grant.</p><div class="table-wrap"><table><tr><th>Agency</th><th>Status</th><th>Actions</th></tr><?php foreach(ins_query('SELECT * FROM agencies ORDER BY id DESC')->fetchAll() as $agency):?><tr><td><?=ie($agency['name'])?> <?=$agency['demo']?'· DEMO':''?></td><td><?=$agency['active']?'Active':'Suspended'?></td><td class="actions"><form method="post"><?php iform('agency_status');ihidden('agency_id',$agency['id']);ihidden('active',!$agency['active']);?><button class="secondary"><?=$agency['active']?'Suspend':'Activate'?></button></form><form method="post"><?php iform('enter_support');ihidden('agency_id',$agency['id']);?><button class="secondary">Open with support permission</button></form></td></tr><?php endforeach ?></table></div></section>
<details class="panel"><summary>Create agency</summary><form method="post" class="form-grid"><?php iform('agency_create');ifield('agency_name');ifield('name','text','','Agency administrator');ifield('email','email');ifield('password','password','','Initial password (12+ characters)');?><label class="check"><input type="checkbox" name="demo" value="1">Demo agency (no real data)</label><button>Create agency & administrator</button></form></details>
<?php elseif($page==='settings'): ins_allow($u,$a,'settings','view');$s=$a['settings']; ?>
<section class="panel"><h2>Agency preferences</h2><form method="post" class="form-grid"><?php iform('settings');ifield('agency_name','text',$a['name']);ifield('contact','textarea',$s['contact']??'');ifield('timezone','text',$s['timezone']);ifield('delivery_time','time',$s['delivery_time']);ifield('reminders','text',implode(',',$s['reminders']),'Reminder offsets in DAYS (30,15,7,1,0,-7)');ifield('due_window','number',$s['due_window']);ifield('categories','textarea',implode("\n",$s['categories']),'Enabled categories — one per line, custom names allowed');ifield('widgets','textarea',implode(',',$s['widgets']),'Dashboard widgets — comma-separated; reorder or remove');?><fieldset class="wide"><legend>Enabled modules</legend><?php foreach(INS_MODULES as $m):?><label class="check"><input type="checkbox" name="modules[]" value="<?=ie($m)?>" <?=in_array($m,$s['modules'],true)?'checked':''?>><?=ie(ucfirst($m))?></label><?php endforeach ?><p>Disabling hides a module and blocks access. Records are preserved; re-enable here to access them again.</p></fieldset><button>Save preferences</button></form></section>
<details class="panel"><summary>Add staff & permissions</summary><form method="post"><?php iform('staff');?><div class="form-grid"><?php ifield('name');ifield('email','email');ifield('password','password','','Initial password (12+ characters)');?></div><?php foreach(INS_MODULES as $m):?><fieldset><legend><?=ie(ucfirst($m))?></legend><?php foreach(['view','edit','delete','export'] as $p):?><label class="check"><input type="checkbox" name="perm[<?=ie($m)?>][]" value="<?=ie($p)?>"><?=ie($p)?></label><?php endforeach ?></fieldset><?php endforeach ?><button>Create staff account</button></form></details>
<section class="panel"><h2>Support permission</h2><p>Permit a named platform administrator to view this agency for one hour. Every access is logged. They cannot edit or export.</p><form method="post" class="inline"><?php iform('support');$admins=[];foreach(ins_query("SELECT id,name FROM users WHERE role='platform' AND active=1")->fetchAll() as $admin)$admins[$admin['id']]=$admin['name'];iselect('admin_id',$admins,'','Platform administrator');?><button>Grant one-hour access</button></form><form method="post"><?php iform('revoke_support');?><button class="secondary">Revoke all support access</button></form></section>
<section class="panel"><h2>Integrations</h2><p>Email · WhatsApp · SMS · Insurer quotes · Payment collection: <strong>Not connected</strong>.</p><p>In-app reminders are available via the CLI scheduler. External adapters, verified rate-table publishing and credential configuration are not enabled in this build. No delivery or payment confirmation is claimed.</p></section>
<?php elseif($page==='dashboard'||$page==='dues'||$page==='reports'): ?>
<?php
if($page!=='dashboard')ins_allow($u,$a,$page);
$events=[];$today=(new DateTimeImmutable('now',new DateTimeZone($a['settings']['timezone'])))->format('Y-m-d');
foreach(ins_query('SELECT e.*,r.data AS record_data,c.data AS client_data FROM events e JOIN records r ON r.id=e.record_id JOIN records c ON c.id=e.client_id WHERE e.agency_id=? AND r.archived=0 AND c.archived=0 ORDER BY due',[$a['id']])->fetchAll() as $e){try{ins_event($u,$a,(int)$e['id']);$e['record']=json_decode($e['record_data'],true);$e['client']=json_decode($e['client_data'],true);$events[]=$e;}catch(DomainException){}}
$open=array_values(array_filter($events,fn($e)=>$e['status']==='open'));$window=(int)$a['settings']['due_window'];$until=(new DateTimeImmutable($today))->modify('+'.$window.' days')->format('Y-m-d');
if($page==='dashboard'):
$metrics=['clients'=>['Total clients',0,'clients'],'policies'=>['Active policies',0,'policies'],'renewals'=>['Renewals · next '.$window.' days',0,'dues','renewal'],'premiums'=>['Premium instalments due',0,'dues','premium'],'overdue'=>['Overdue payment events',0,'dues','overdue'],'expired'=>['Coverage periods ended',0,'policies'],'sip'=>['Upcoming contributions',0,'dues','contribution'],'maturities'=>['Upcoming maturities',0,'dues','maturity'],'followups'=>['Today’s follow-ups',0,'dues','followup'],'collections'=>['Recorded collections',0,'reports'],'pending'=>['Outstanding amounts',0,'dues'],'leads'=>['Open leads',0,'leads']];
foreach(['clients','policies','leads'] as $kind){try{$list=ins_records($u,$a,$kind);foreach($list as $r){if($kind==='clients')$metrics['clients'][1]++;if($kind==='leads'&&!in_array($r['data']['stage'],['converted','lost'],true))$metrics['leads'][1]++;if($kind==='policies'){if($r['data']['status']==='active'&&(empty($r['data']['expiry'])||$r['data']['expiry']>=$today))$metrics['policies'][1]++;if(!empty($r['data']['expiry'])&&$r['data']['expiry']<$today)$metrics['expired'][1]++;}}}catch(DomainException){}}
foreach($open as $e){$near=$e['due']>=$today&&$e['due']<=$until;if($e['type']==='renewal'&&$near)$metrics['renewals'][1]++;if($e['type']==='premium'&&$e['due']<=$until)$metrics['premiums'][1]++;if($e['type']==='contribution'&&$near)$metrics['sip'][1]++;if($e['type']==='maturity'&&$near)$metrics['maturities'][1]++;if($e['type']==='followup'&&$e['due']===$today)$metrics['followups'][1]++;if(in_array($e['type'],['premium','contribution'],true)){$metrics['pending'][1]+=$e['amount']-$e['received'];if($e['due']<$today)$metrics['overdue'][1]++;}}
foreach($events as $e)$metrics['collections'][1]+=$e['received'];
?><div class="metrics"><?php foreach($a['settings']['widgets'] as $key):if(!isset($metrics[$key]))continue;$m=$metrics[$key];?><a class="metric" href="<?=ie(iu($m[2],['filter'=>$m[3]??$key]))?>"><span><?=ie($m[0])?></span><strong><?=in_array($key,['collections','pending'],true)?im($m[1]):$m[1]?></strong><small>View records →</small></a><?php endforeach ?></div><p class="muted">Coverage expiry, payment overdue status and contribution status are tracked independently. A late payment does not automatically lapse a policy.</p>
<?php endif ?>
<section class="panel"><div class="section-head"><h2><?=$page==='reports'?'Collections & outstanding ledger':'Attention queue'?></h2><a class="button secondary" href="<?=ie(iu('clients',['new'=>1]))?>">Add client</a></div>
<form method="get" class="filters"><?php ihidden('page',$page);iselect('filter',[''=>'All open events','today'=>'Today','7'=>'Next 7 days','15'=>'Next 15 days','30'=>'Next 30 days','overdue'=>'Overdue payments','renewal'=>'Coverage renewal','premium'=>'Premium','contribution'=>'Contribution','maturity'=>'Maturity','followup'=>'Follow-up'],$_GET['filter']??'');ifield('from','date',$_GET['from']??'');ifield('to','date',$_GET['to']??'');ifield('q','search',$_GET['q']??'','Client / provider / category');iselect('contacted',[''=>'Any contact status','0'=>'Not contacted','1'=>'Contacted'],$_GET['contacted']??'');?><button>Filter</button></form>
<?php $filter=$_GET['filter']??'';$filtered=array_values(array_filter($page==='reports'?$events:$open,function($e)use($filter,$today,$until){if(($_GET['from']??'')&&$e['due']<$_GET['from'])return false;if(($_GET['to']??'')&&$e['due']>$_GET['to'])return false;if(($_GET['contacted']??'')!==''&&(string)$e['contacted']!==$_GET['contacted'])return false;if(($_GET['q']??'')&&stripos(ins_json([$e['client'],$e['record']]),$_GET['q'])===false)return false;if($filter==='today')return $e['due']===$today;if(ctype_digit((string)$filter))return $e['due']>=$today&&$e['due']<=(new DateTimeImmutable($today))->modify('+'.$filter.' days')->format('Y-m-d');if($filter==='overdue')return $e['due']<$today&&in_array($e['type'],['premium','contribution'],true)&&$e['amount']>$e['received'];if(in_array($filter,['renewal','premium','contribution','maturity','followup'],true))return $e['type']===$filter;return true;}));?>
<p><?=count($filtered)?> matching events</p><div class="event-list"><?php foreach(array_slice($filtered,0,100) as $e):$days=(int)(new DateTimeImmutable($today))->diff(new DateTimeImmutable($e['due']))->format('%r%a');?><article class="event"><div><a href="<?=ie(iu('clients',['id'=>$e['client_id']]))?>"><strong><?=ie($e['client']['name'])?></strong></a><p><?=ie($e['record']['name'])?> · <?=ie($e['record']['provider']??'')?></p><span class="badge"><?=ie($e['type'])?></span> <?=ie($e['due'])?> · <?=$days<0?abs($days).' days overdue':$days.' days remaining'?><p>Due <?=im((int)$e['amount'])?> · recorded <?=im((int)$e['received'])?> · balance <?=im((int)$e['amount']-(int)$e['received'])?> · <?=ie($e['status'])?></p></div><div class="actions"><a class="button secondary" href="tel:<?=ie(preg_replace('/[^+0-9]/','',$e['client']['phone']??''))?>">Call</a><form method="post"><?php iform('contacted');ihidden('event_id',$e['id']);?><button class="secondary">Mark contacted</button></form></div>
<?php if($e['status']==='open'&&in_array($e['type'],['premium','contribution'],true)):?><details><summary>Record payment</summary><form method="post" class="form-grid"><?php iform('payment');ihidden('event_id',$e['id']);ifield('amount','number',($e['amount']-$e['received'])/100);ifield('paid_at','date',$today);ifield('reference');?><p>Manual record only — not provider-confirmed.</p><button>Save payment</button></form></details><?php elseif($e['status']==='open'&&$e['type']==='renewal'):?><details><summary>Record renewal</summary><form method="post" class="form-grid"><?php iform('renew');ihidden('event_id',$e['id']);ifield('start','date');ifield('expiry','date');ifield('premium','number');ifield('next_due','date');?><p>A new linked coverage record will be created. The previous period is kept.</p><button>Save renewal</button></form></details><?php endif ?></article><?php endforeach ?><?php if(!$filtered):?><p class="empty">No matching events. Save a policy or investment with relevant dates to populate this queue.</p><?php endif ?></div></section>
<details class="panel"><summary>In-app reminders</summary><p>Generated by the scheduler; opening this page does not run the job. External channels: Not connected.</p><?php foreach(ins_query("SELECT n.*,e.record_id,e.type,e.due FROM notifications n JOIN events e ON e.id=n.event_id WHERE n.agency_id=? AND e.status='open' AND n.revision=e.revision ORDER BY n.id DESC LIMIT 100",[$a['id']])->fetchAll() as $n){try{ins_event($u,$a,(int)$n['event_id']);echo '<p>'.ie($n['type'].' · '.$n['due'].' · '.$n['state'].' · '.$n['created_at']).'</p>';}catch(DomainException){}}?></details>
<?php elseif($page==='calculators'):ins_allow($u,$a,'calculators'); ?>
<section class="panel"><h2>Financial projections</h2><p>Assumed returns, not guaranteed. Monthly compounding; contributions at month-end; annual step-up after each 12 contributions. FD/RD are mathematical estimates, not bank maturity quotes. No taxes or fees included.</p><form method="get" class="form-grid"><?php ihidden('page','calculators');iselect('type',['sip'=>'SIP','step-up'=>'Step-up SIP','lump-sum'=>'Lump sum','goal'=>'Goal planning','fd'=>'FD estimate','rd'=>'RD estimate','retirement'=>'Retirement accumulation'],$_GET['type']??'sip');ifield('amount','number',$_GET['amount']??1000,'Contribution / lump sum / target amount');ifield('rate','number',$_GET['rate']??8,'Assumed annual return (%)');ifield('months','number',$_GET['months']??120);ifield('step','number',$_GET['step']??0,'Annual contribution increase (%)');ifield('initial','number',$_GET['initial']??0,'Existing savings');?><button>Calculate projection</button></form><?php if(isset($_GET['type'])){$projection=ins_projection($_GET['type'],(float)$_GET['amount'],(float)$_GET['rate'],(int)$_GET['months'],(float)$_GET['step'],(float)$_GET['initial']);?><div class="alert"><h3><?=ie($projection['label'])?>: <?=im((int)round($projection['result']*100))?></h3><p>Invested amount: <?=im((int)round($projection['invested']*100))?> · Projection only, not actual portfolio valuation.</p></div><?php } ?></section><section class="panel"><h2>Insurance premiums</h2><strong>Quote required</strong><p>No verified pricing API or product-specific rate table is configured. Record an official provider quote in Plans & Costing. We do not invent premiums.</p></section>
<?php elseif($page==='clients'&&!empty($_GET['id'])): require __DIR__.'/client-hub.php'; ?>
<?php elseif(in_array($page,['policies','investments','leads','claims','commissions'],true)&&!empty($_GET['id'])&&empty($_GET['edit'])):
$r=ins_record($u,$a,(int)$_GET['id']);if($r['kind']!==$page)throw new DomainException('Wrong record type.'); ?>
<section class="panel"><div class="section-head"><h2><?=ie($r['data']['name'])?></h2><?php if($r['client_id']):?><a class="button" href="<?=ie(iu('clients',['id'=>$r['client_id']]))?>">Open client workspace</a><?php endif ?><a class="button secondary" href="<?=ie(iu($page,['id'=>$r['id'],'edit'=>1]))?>">Edit</a></div><dl class="record-details"><?php foreach(ins_fields($page) as $key=>$type):$value=$r['data'][$key]??'';if($value==='')continue;?><dt><?=ie(ucwords(str_replace('_',' ',$key)))?></dt><dd><?=nl2br(ie($type==='money'?im((int)$value):$value))?></dd><?php endforeach ?></dl></section>
<?php elseif($page==='documents'):ins_allow($u,$a,'documents'); ?>
<section class="panel"><h2>Private documents</h2><form method="post" enctype="multipart/form-data" class="form-grid"><?php iform('upload');iselect('client_id',ioptions(ins_records($u,$a,'clients')));ifield('label');?><label>PDF / JPEG / PNG · max 5 MB<input type="file" name="document" accept="application/pdf,image/jpeg,image/png" required></label><button>Upload privately</button></form><ul><?php foreach(ins_records($u,$a,'documents') as $r):?><li><?=ie($r['data']['name'])?> <a href="<?=ie(iu('documents',['download'=>$r['id']]))?>">Download</a></li><?php endforeach ?></ul></section>
<?php elseif(in_array($page,['clients','policies','investments','leads','plans','claims','commissions'],true)):ins_allow($u,$a,$page);$selected=isset($_GET['id'])?ins_record($u,$a,(int)$_GET['id']):null;if($selected&&$selected['kind']!==$page)throw new DomainException('Wrong record type.'); ?>
<?php if($selected&&isset($selected['data']['plan_snapshot'])):$q=$selected['data'];?><section class="panel quote"><h2><?=ie($q['agency_name'])?></h2><p><?=ie($q['agency_contact'])?></p><h3>Quotation for <?=ie($q['client_name'])?></h3><p><?=ie($q['name'])?> · <?=ie($q['label'])?></p><strong><?=im($q['amount'])?></strong><p>Source: <?=ie($q['source'])?></p><p>Assumptions: <?=nl2br(ie($q['assumptions']))?></p><p>Valid until: <?=ie($q['valid_until']?:'Not supplied')?> · Recorded: <?=ie($q['timestamp'])?></p><p>Product version: <?=ie($q['plan_snapshot']['product_version']??'Not supplied')?></p><p>Exclusions: <?=nl2br(ie($q['plan_snapshot']['exclusions']??'Not supplied'))?></p><button id="print">Print / Save as PDF</button><p class="muted">Snapshot retained even if the catalogue changes. This is not proof of cover.</p></section>
<?php else: ?>
<?php if($selected&&$page==='clients'):$c=$selected['data'];?><section class="panel"><h2><?=ie($c['name'])?></h2><p><?=ie($c['email'])?> · <?=ie($c['phone'])?></p><div class="actions"><a class="button secondary" href="tel:<?=ie(preg_replace('/[^+0-9]/','',$c['phone']))?>">Call</a><?php if(in_array($c['consent'],['email','both'],true)):?><a class="button secondary" href="mailto:<?=ie($c['email'])?>">Compose email</a><?php endif ?><?php if(in_array($c['consent'],['whatsapp','both'],true)&&preg_match('/^\+?[1-9]\d{7,14}$/',preg_replace('/[\s()-]/','',$c['phone']))):?><a class="button secondary" href="https://wa.me/<?=ie(preg_replace('/\D/','',$c['phone']))?>?text=<?=rawurlencode('Hello '.$c['name'].', ')?>" target="_blank" rel="noopener">Compose WhatsApp</a><?php endif ?></div><p class="muted">Opening a composer does not confirm delivery. Use international phone format.</p><details><summary>Family & notes</summary><p><?=nl2br(ie($c['family']))?></p><p><?=nl2br(ie($c['notes']))?></p></details><?php foreach(['policies','investments','leads','documents'] as $linked){if(!in_array($linked,$a['settings']['modules'],true))continue;try{$linkedRows=array_values(array_filter(ins_records($u,$a,$linked),fn($r)=>(int)$r['client_id']===$selected['id']));echo '<details><summary>'.ie(ucfirst($linked)).' ('.count($linkedRows).')</summary>';if($linked!=='documents')ilist($linkedRows,$linked);else foreach($linkedRows as $doc)echo '<p><a href="'.ie(iu('documents',['download'=>$doc['id']])).'">'.ie($doc['data']['name']).'</a></p>';echo '</details>';}catch(DomainException){}}?><a href="<?=ie(iu('dues',['q'=>$c['name']]))?>">Payments & follow-ups →</a></section><?php endif ?>
<section class="panel"><div class="section-head"><h2><?=ie($selected?'Edit '.$selected['data']['name']:ucfirst($page))?></h2><div class="actions"><a class="button" href="<?=ie(iu($page,['new'=>1]))?>">Add new</a><a class="button secondary" href="<?=ie(iu($page,['export'=>$page]))?>">Export CSV</a></div></div>
<?php if(isset($_GET['new'])||$selected):$d=$selected['data']??[];?><form method="post" class="form-grid"><?php iform('save');ihidden('kind',$page);ihidden('id',$selected['id']??0);ihidden('version',$selected['version']??0);
if(!in_array($page,['clients','plans'],true))iselect('client_id',ioptions(ins_records($u,$a,'clients')),$selected['client_id']??'',$page==='leads'?'Client (optional for agency admin)':'Client');
foreach(ins_fields($page) as $key=>$type){$v=$d[$key]??'';if($type==='money')ifield($key,'number',$v!==''?$v/100:'');elseif($type==='frequency')iselect($key,array_combine(['once','weekly','monthly','quarterly','half-yearly','yearly'],['One time','Weekly','Monthly','Quarterly','Half yearly','Yearly']),$v?:'once');elseif($type==='category')iselect($key,array_combine($a['settings']['categories'],$a['settings']['categories']),$v);elseif(str_starts_with($type,'select:')){$opts=explode(',',substr($type,7));iselect($key,array_combine($opts,$opts),$v?:$opts[0]);}else ifield($key,$type,$v);}
$staff=[];foreach(ins_query('SELECT id,name FROM users WHERE agency_id=? AND active=1',[$a['id']])->fetchAll() as $st)$staff[$st['id']]=$st['name'];iselect('assigned_id',$staff,$selected['assigned_id']??$u['id']);?><div class="wide"><p class="muted">Family / insured members: one person per line with relationship and DOB. Category-specific details: include health members/floater/add-ons, motor registration/model/IDV/NCB, or life terms as applicable. Custom fields are stored as notes in this first build.</p><button>Save record</button> <a class="button secondary" href="<?=ie(iu($page))?>">Cancel</a></div></form><?php if($selected):?><form method="post" class="archive-form"><?php iform('archive');ihidden('id',$selected['id']);?><button class="secondary"><?=$selected['archived']?'Restore record':'Archive record'?></button></form><?php if($page==='leads'&&$d['stage']!=='converted'):?><form method="post"><?php iform('convert');ihidden('id',$selected['id']);?><button>Convert to client</button></form><?php endif ?><?php endif ?>
<?php else:$rows=ins_records($u,$a,$page,!empty($_GET['archived']));$search=trim($_GET['q']??'');if($search)$rows=array_values(array_filter($rows,fn($r)=>stripos(ins_json($r['data']),$search)!==false));if(($_GET['filter']??'')==='expired')$rows=array_values(array_filter($rows,fn($r)=>!empty($r['data']['expiry'])&&$r['data']['expiry']<date('Y-m-d')));if(($_GET['sort']??'')==='name')usort($rows,fn($x,$y)=>strcasecmp($x['data']['name'],$y['data']['name']));$total=count($rows);$p=max(1,(int)($_GET['p']??1));?>
<form method="get" class="filters"><?php ihidden('page',$page);ifield('q','search',$search,'Search');iselect('sort',['new'=>'Newest first','name'=>'Name A–Z'],$_GET['sort']??'new');iselect('archived',['0'=>'Active records','1'=>'Archived records'],$_GET['archived']??'0');?><button>Apply</button></form><?php ilist(array_slice($rows,($p-1)*20,20),$page);?><footer class="pagination"><span><?=$total?> records · page <?=$p?></span><?php if($p>1):?><a href="<?=ie(iu($page,['p'=>$p-1,'q'=>$search,'archived'=>$_GET['archived']??0,'sort'=>$_GET['sort']??'new']))?>">Previous</a><?php endif ?><?php if($p*20<$total):?><a href="<?=ie(iu($page,['p'=>$p+1,'q'=>$search,'archived'=>$_GET['archived']??0,'sort'=>$_GET['sort']??'new']))?>">Next</a><?php endif ?></footer><?php endif ?></section>
<?php if($page==='clients'):?><details class="panel" <?=is_array($result)?'open':''?>><summary>Import clients · CSV mapping & review</summary><p>Excel users: save your worksheet as CSV first. Existing email/phone matches are skipped, never overwritten. Imported contacts have no messaging consent by default.</p><form method="post" enctype="multipart/form-data"><?php iform('import_preview');?><label>CSV file<input type="file" name="csv" accept=".csv,text/csv" required></label><div class="form-grid"><?php foreach(['name','email','phone','city','notes'] as $key)ifield('map_'.$key,'text',$key,ucfirst($key).' column heading');?></div><button>Preview import</button></form><?php if(is_array($result)):?><table><tr><th>Name</th><th>Review</th></tr><?php foreach($result as $r):?><tr><td><?=ie($r['data']['name'])?></td><td><?=ie($r['issue'])?></td></tr><?php endforeach ?></table><form method="post"><?php iform('import_commit');?><button>Import valid rows only</button></form><?php endif ?></details><?php endif ?>
<?php if($page==='plans'):?><details class="panel"><summary>Save official quotation</summary><form method="post" class="form-grid"><?php iform('quote');iselect('client_id',ioptions(ins_records($u,$a,'clients')));iselect('plan_id',ioptions(array_values(array_filter(ins_records($u,$a,'plans'),fn($r)=>!isset($r['data']['plan_snapshot'])))));ifield('amount','number','','Official quoted premium (total)');ifield('source','text','','Provider quote reference / official source');ifield('valid_until','date');ifield('assumptions','textarea','','Coverage, insured members, term, exclusions and breakdown');?><button>Save immutable quotation</button></form></details><?php endif ?>
<?php endif ?>
<?php else: throw new DomainException('Page not found.');endif;}catch(DomainException $ex){echo '<p class="alert error" role="alert">'.ie($ex->getMessage()).'</p>';}catch(Throwable $ex){echo '<p class="alert error">Unable to display this section. Check setup and retry.</p>';} ?>
</main><?php endif ?></body></html>
