<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/auth.php';
$checks=0;
function check(bool $ok,string $label): void {global $checks;if(!$ok)throw new RuntimeException('FAILED: '.$label);$checks++;echo "PASS $label\n";}
function denied(callable $fn,string $label): void {try{$fn();}catch(DomainException){check(true,$label);return;}check(false,$label);}
ins_query('INSERT INTO agencies(name,settings,demo) VALUES(?,?,1)',['Test A',ins_json(ins_defaults())]);$aid=(int)ins_db()->lastInsertId();
ins_query('INSERT INTO agencies(name,settings,demo) VALUES(?,?,1)',['Test B',ins_json(ins_defaults())]);$bid=(int)ins_db()->lastInsertId();
$uid=ins_create_user($aid,'admin-a@example.test','Admin A','Test-only-password-9283','admin');$vid=ins_create_user($bid,'admin-b@example.test','Admin B','Test-only-password-9283','admin');
$sid=ins_create_user($aid,'staff@example.test','Staff','Test-only-password-9283','staff',['clients'=>['view'],'policies'=>['view'],'dues'=>['view']]);
$pid=ins_create_user(null,'platform@example.test','Platform','Test-only-password-9283','platform');
$u=ins_user($uid);$v=ins_user($vid);$staff=ins_user($sid);$platform=ins_user($pid);$a=ins_context($u,$aid);$b=ins_context($v,$bid);
$client=ins_transaction(fn()=>ins_save($u,$a,'clients',['name'=>'Alice','email'=>'alice@example.test','phone'=>'+919876543210','consent'=>'none','assigned_id'=>$uid]));
$other=ins_transaction(fn()=>ins_save($v,$b,'clients',['name'=>'Bob','consent'=>'none','assigned_id'=>$vid]));
denied(fn()=>ins_record($u,$a,$other),'Cross-agency direct record ID denied');
denied(fn()=>ins_context($u,$bid),'Cross-agency context denied');
denied(fn()=>ins_context($platform,$aid),'Platform cannot access private agency without grant');
denied(fn()=>ins_record($staff,$a,$client),'Staff cannot read unassigned client');
denied(fn()=>ins_save($staff,$a,'clients',['name'=>'Denied','consent'=>'none']),'Staff write permission enforced');
check(count(ins_records($staff,$a,'clients'))===0,'Staff list filtered by assignment');
denied(fn()=>ins_allow($staff,$a,'clients','export'),'Staff export permission enforced');
denied(fn()=>ins_transaction(fn()=>ins_save($u,$a,'clients',['name'=>'Duplicate','email'=>'alice@example.test','consent'=>'none','assigned_id'=>$uid])),'Duplicate email rejected');
$policyInput=['name'=>'Health policy','category'=>'Health','status'=>'active','frequency'=>'monthly','premium'=>'1000','coverage'=>'500000','start'=>'2024-01-01','expiry'=>'2024-12-31','next_due'=>'2024-01-31','client_id'=>$client,'assigned_id'=>$uid];
$policy=ins_transaction(fn()=>ins_save($u,$a,'policies',$policyInput));
$investment=ins_transaction(fn()=>ins_save($u,$a,'investments',['name'=>'SIP','category'=>'Mutual funds / SIP','status'=>'active','frequency'=>'monthly','amount'=>'500','start'=>'2024-01-01','next_due'=>'2024-01-31','client_id'=>$client,'assigned_id'=>$uid]));
check(ins_record($u,$a,$investment)['data']['end']==='','SIP allows no end date');
$event=ins_query("SELECT * FROM events WHERE record_id=? AND type='premium'",[$policy])->fetch();
check(ins_query("SELECT due FROM events WHERE record_id=? AND type='renewal'",[$policy])->fetchColumn()==='2024-12-31','Coverage expiry independent of premium due');
denied(fn()=>ins_event($v,$b,(int)$event['id']),'Cross-agency event denied');
ins_transaction(fn()=>ins_pay($u,$a,(int)$event['id'],40000,'2024-01-31','Partial'));
$partial=ins_query('SELECT * FROM events WHERE id=?',[$event['id']])->fetch();check($partial['status']==='open'&&(int)$partial['received']===40000,'Partial payment keeps remaining balance');
ins_transaction(fn()=>ins_pay($u,$a,(int)$event['id'],60000,'2024-01-31','Balance'));
check(ins_query('SELECT status FROM events WHERE id=?',[$event['id']])->fetchColumn()==='paid','Fully paid event closed');
check(ins_query("SELECT due FROM events WHERE record_id=? AND type='premium' AND status='open'",[$policy])->fetchColumn()==='2024-02-29','Leap February recurrence');
$feb=ins_query("SELECT * FROM events WHERE record_id=? AND type='premium' AND status='open'",[$policy])->fetch();ins_transaction(fn()=>ins_pay($u,$a,(int)$feb['id'],100000,'2024-02-29','Next'));
check(ins_query("SELECT due FROM events WHERE record_id=? AND type='premium' AND status='open'",[$policy])->fetchColumn()==='2024-03-31','Original month-end anchor retained');
check(ins_next('2023-01-31','monthly',1)==='2023-02-28','Non-leap February');
$first=ins_transaction(fn()=>ins_job(new DateTimeImmutable('2024-01-30T10:00:00Z')));$second=ins_transaction(fn()=>ins_job(new DateTimeImmutable('2024-01-30T10:00:00Z')));
check($first>0&&$second===0,'Background reminder reruns are idempotent');
check((int)ins_query("SELECT count(*) FROM notifications WHERE channel<>'in-app'")->fetchColumn()===0,'Unconfigured providers never claim delivery');
$r=ins_record($u,$a,$investment);$input=$r['data'];$input['amount']/=100;$input+=['version'=>$r['version'],'client_id'=>$client,'assigned_id'=>$uid];$input['status']='paused';ins_transaction(fn()=>ins_save($u,$a,'investments',$input,$investment));
check((int)ins_query("SELECT count(*) FROM events WHERE record_id=? AND status='open'",[$investment])->fetchColumn()===0,'Paused SIP cancels open reminders');
$off=$a;$off['settings']['modules']=array_values(array_diff($off['settings']['modules'],['policies']));denied(fn()=>ins_record($u,$off,$policy),'Disabled module direct access denied');check(ins_record($u,$a,$policy)['id']===$policy,'Disabling preserves existing record');
$p=ins_projection('sip',1000,0,12);check($p['result']===12000.0&&$p['invested']===12000.0,'Zero-return SIP reference');
$p=ins_projection('lump-sum',1000,12,12);check(abs($p['result']-1126.83)<0.01,'Monthly compound growth reference');
$p=ins_projection('goal',12000,0,12);check($p['result']===1000.0,'Zero-return goal contribution');
denied(fn()=>ins_projection('sip',-1,8,12),'Invalid calculator input denied');
denied(fn()=>ins_date('2024-02-30'),'Impossible date rejected');
ins_query('INSERT INTO support(agency_id,admin_id,expires_at) VALUES(?,?,?)',[$aid,$pid,gmdate('c',time()+3600)]);check(ins_context($platform,$aid)['id']===$aid,'Explicit support grant enables logged read access');denied(fn()=>ins_allow($platform,$a,'clients','edit'),'Support cannot edit');denied(fn()=>ins_allow($platform,$a,'clients','export'),'Support cannot export');
echo "All $checks domain checks passed.\n";
require dirname(__DIR__).'/src/meeting.php';
$demoUser=ins_transaction(fn()=>ins_seed_demo($pid));
check(ins_user($demoUser)['role']==='admin','Meeting demo provisioned');
check(ins_transaction(fn()=>ins_seed_demo($pid))===$demoUser,'Demo initialization does not duplicate records');
require dirname(__DIR__).'/src/demo-history.php';
$du=ins_user($demoUser);$da=ins_context($du,(int)$du['agency_id']);
ins_demo_history($du,$da);ins_demo_history($du,$da);
check((int)ins_query('SELECT COUNT(*) FROM record_revisions WHERE agency_id=? AND version<0',[$da['id']])->fetchColumn()===60,'Five demo periods per policy, without duplicates');
