<?php
$e = static fn(mixed $value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$ctPageMeta = [
    'dashboard'=>['Dashboard','Sales, billing, collections and stock at a glance.'],
    'enquiries'=>['Enquiries','Capture enquiries and convert them into business.'],
    'customers'=>['Customers','Manage GST profiles, contacts and billing cycles.'],
    'quotations'=>['Quotations','Prepare, share and follow commercial quotations.'],
    'orders'=>['Orders','Manage confirmed sales and reserved stock.'],
    'invoices'=>['Billing','Create GST invoices from unbilled orders.'],
    'payments'=>['Payments','Track collections and outstanding balances.'],
    'products'=>['Products','Manage the chemical catalogue, tax and pricing.'],
    'inventory'=>['Inventory','Monitor stock and reorder requirements.'],
    'purchases'=>['Purchase','Manage suppliers, purchase orders and receipts.'],
    'dispatch'=>['Dispatch','Track delivery notes, transport and proof of delivery.'],
    'reports'=>['Reports','Review sales, tax, stock and receivables.'],
    'documents'=>['Documents','Keep commercial and compliance files organised.'],
    'settings'=>['Settings','Company, GST, bank and invoice configuration.'],
];
[$ctTitle,$ctSubtitle] = $ctPageMeta[$chemtechPage];
$ctNavGroups = [
    'Overview'=>['dashboard'=>'Dashboard'],
    'Sales'=>['enquiries'=>'Enquiries','customers'=>'Customers','quotations'=>'Quotations','orders'=>'Orders','invoices'=>'Billing'],
    'Accounts'=>['payments'=>'Payments'],
    'Operations'=>['products'=>'Products','inventory'=>'Inventory','purchases'=>'Purchase','dispatch'=>'Dispatch'],
    'Insights'=>['reports'=>'Reports','documents'=>'Documents','settings'=>'Settings'],
];
$ctSales = array_sum(array_map(static fn(array $invoice): int => (int) ($invoice['total_paise'] ?? 0), $chemtechInvoices));
$ctCollected = array_sum(array_map(static fn(array $invoice): int => (int) ($invoice['paid_paise'] ?? 0), $chemtechInvoices));
$ctOutstanding = max(0, $ctSales - $ctCollected);
$ctUnbilled = array_values(array_filter($chemtechOrders, static fn(array $order): bool => ($order['billing_status'] ?? 'unbilled') === 'unbilled'));
$ctUnbilledValue = array_sum(array_map(static fn(array $order): int => (int) ($order['total_paise'] ?? 0), $ctUnbilled));
$ctLowStock = array_values(array_filter($chemtechProducts, static fn(array $product): bool => (int) ($product['stock_milli'] ?? 0) <= (int) ($product['reorder_milli'] ?? 0)));
$ctOpenInvoices = array_values(array_filter($chemtechInvoices, static fn(array $invoice): bool => (int) ($invoice['paid_paise'] ?? 0) < (int) ($invoice['total_paise'] ?? 0)));
$ctOverdue = array_values(array_filter($ctOpenInvoices, static fn(array $invoice): bool => (string) ($invoice['due_date'] ?? '') < date('Y-m-d')));
$ctAccent = '#faa61d';
?>
<div class="ct-workspace">
    <aside class="ct-sidebar" data-ct-sidebar>
        <div class="ct-brand">
            <span><?= $e($chemtechSettings['short_name']) ?></span>
            <strong><?= $e($chemtechSettings['company_name']) ?></strong>
            <button type="button" data-ct-sidebar-toggle aria-label="Collapse navigation">‹</button>
        </div>
        <nav aria-label="ChemTech navigation">
            <?php foreach($ctNavGroups as $group=>$items): ?>
                <section><small><?= $e($group) ?></small><?php foreach($items as $page=>$label): ?><a class="<?= $chemtechPage===$page?'active':'' ?>" href="?business=chemtech&amp;page=<?= $e($page) ?>"><b><?= $e($label) ?></b></a><?php endforeach; ?></section>
            <?php endforeach; ?>
        </nav>
        <a class="ct-back" href="./"><span>←</span><b>All businesses</b></a>
    </aside>

    <main class="ct-main">
        <header class="ct-topbar">
            <div class="ct-heading"><button class="ct-mobile-menu" type="button" data-ct-sidebar-toggle aria-label="Open navigation">Menu</button><span class="ct-breadcrumb"><?= $e($chemtechSettings['company_name']) ?> / <?= $e($ctTitle) ?></span><h1><?= $e($ctTitle) ?></h1><p><?= $e($ctSubtitle) ?></p></div>
            <div class="ct-top-actions"><button class="ct-theme" data-theme-toggle type="button" aria-label="Switch theme"><span>☼</span></button><?php if($chemtechPage==='dashboard'): ?><a class="ct-button primary" href="?business=chemtech&amp;page=orders">Create order</a><?php endif; ?></div>
        </header>
        <?php if($notice): ?><div class="ct-notice" role="status"><?= $e($notice) ?></div><?php endif; ?>

        <?php if($chemtechPage==='dashboard'): ?>
            <section class="ct-summary" aria-label="Business overview">
                <a href="?business=chemtech&amp;page=invoices"><span>Invoiced sales</span><strong><?= chemtechMoney($ctSales) ?></strong><small><?= count($chemtechInvoices) ?> invoices</small></a>
                <a href="?business=chemtech&amp;page=payments"><span>Outstanding</span><strong><?= chemtechMoney($ctOutstanding) ?></strong><small><?= count($ctOpenInvoices) ?> open invoices</small></a>
                <a href="?business=chemtech&amp;page=invoices"><span>Unbilled orders</span><strong><?= chemtechMoney($ctUnbilledValue) ?></strong><small><?= count($ctUnbilled) ?> ready for billing</small></a>
                <a href="?business=chemtech&amp;page=inventory"><span>Low stock</span><strong><?= count($ctLowStock) ?></strong><small><?= count($chemtechProducts) ?> products tracked</small></a>
            </section>
            <section class="ct-dashboard-grid">
                <article class="ct-card ct-index">
                    <header class="ct-section-head"><div><h2>Recent orders</h2><p>Latest confirmed sales orders</p></div><a href="?business=chemtech&amp;page=orders">View all</a></header>
                    <?php if(!$chemtechOrders): ?><div class="ct-empty"><b>No orders yet</b><span>Create an order when you are ready to begin.</span><a class="ct-button" href="?business=chemtech&amp;page=orders">Open orders</a></div><?php else: ?><div class="ct-table-wrap"><table class="ct-table"><thead><tr><th>Order</th><th>Customer</th><th>Product</th><th>Total</th><th>Billing</th></tr></thead><tbody><?php foreach(array_slice($chemtechOrders,0,8) as $order): ?><tr><td><b><?= $e($order['order_number']) ?></b><small><?= $e(date('d M Y',strtotime((string)$order['created_at']))) ?></small></td><td><?= $e($order['customer_name']) ?></td><td><?= $e($order['product_name']) ?></td><td><?= chemtechMoney((int)$order['total_paise']) ?></td><td><span class="ct-status <?= $e($order['billing_status']) ?>"><?= $e(ucfirst($order['billing_status'])) ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
                </article>
                <aside class="ct-stack">
                    <article class="ct-card ct-attention"><header class="ct-section-head"><div><h2>Needs attention</h2><p>Items requiring action</p></div></header><a href="?business=chemtech&amp;page=invoices"><span>Unbilled orders<small>Ready to invoice</small></span><strong><?= count($ctUnbilled) ?></strong></a><a href="?business=chemtech&amp;page=payments"><span>Overdue invoices<small>Past payment date</small></span><strong><?= count($ctOverdue) ?></strong></a><a href="?business=chemtech&amp;page=inventory"><span>Low-stock products<small>At or below reorder level</small></span><strong><?= count($ctLowStock) ?></strong></a></article>
                    <article class="ct-card ct-shortcuts"><header class="ct-section-head"><div><h2>Quick access</h2></div></header><nav><a href="?business=chemtech&amp;page=customers">Customers <span>→</span></a><a href="?business=chemtech&amp;page=products">Products <span>→</span></a><a href="?business=chemtech&amp;page=payments">Receivables <span>→</span></a><a href="?business=chemtech&amp;page=reports">Reports <span>→</span></a></nav></article>
                </aside>
            </section>

        <?php elseif($chemtechPage==='customers'): ?>
            <section class="ct-card ct-index"><header class="ct-index-toolbar"><div><h2>All customers</h2><span><?= count($chemtechCustomers) ?> total</span></div><div class="ct-toolbar-actions"><label class="ct-search"><span>Search</span><input type="search" placeholder="Search customers" data-ct-table-filter="ct-customer-table"></label><button class="ct-button primary" type="button" data-dialog-open="ct-customer-dialog">Add customer</button></div></header><div class="ct-table-wrap"><table class="ct-table" id="ct-customer-table"><thead><tr><th>Company</th><th>Contact</th><th>GST profile</th><th>Billing cycle</th><th>Credit</th></tr></thead><tbody><?php foreach($chemtechCustomers as $customer): ?><tr><td><b><?= $e($customer['name']) ?></b><small><?= $e($customer['state']?:'State not set') ?></small></td><td><?= $e($customer['contact_person']?:'—') ?><small><?= $e($customer['email']?:$customer['phone']) ?></small></td><td><?= $e($customer['gstin']?:'Unregistered') ?><small>State code <?= $e($customer['state_code']?:'—') ?></small></td><td><?= $e(ucwords(str_replace('_',' ',$customer['billing_cycle']))) ?></td><td><?= (int)$customer['credit_days'] ?> days</td></tr><?php endforeach; ?></tbody></table></div></section>

        <?php elseif($chemtechPage==='products'): ?>
            <section class="ct-card ct-index"><header class="ct-index-toolbar"><div><h2>Product catalogue</h2><span><?= count($chemtechProducts) ?> products</span></div><div class="ct-toolbar-actions"><label class="ct-search"><span>Search</span><input type="search" placeholder="Search products" data-ct-table-filter="ct-product-table"></label><button class="ct-button primary" type="button" data-dialog-open="ct-product-dialog">Add product</button></div></header><div class="ct-table-wrap"><table class="ct-table" id="ct-product-table"><thead><tr><th>Product</th><th>Category</th><th>HSN / GST</th><th>Selling price</th><th>Available stock</th></tr></thead><tbody><?php foreach($chemtechProducts as $product): $low=(int)$product['stock_milli']<=(int)$product['reorder_milli']; ?><tr><td><b><?= $e($product['name']) ?></b><small><?= $e($product['sku']) ?></small></td><td><?= $e($product['category']?:'Uncategorised') ?></td><td><?= $e($product['hsn']?:'—') ?><small><?= number_format($product['gst_rate_bps']/100,2) ?>% GST</small></td><td><?= chemtechMoney((int)$product['sale_price_paise']) ?> / <?= $e($product['unit']) ?></td><td><span class="ct-status <?= $low?'warning':'ready' ?>"><?= number_format($product['stock_milli']/1000,3) ?> <?= $e($product['unit']) ?></span></td></tr><?php endforeach; ?></tbody></table></div></section>

        <?php elseif($chemtechPage==='orders'): ?>
            <section class="ct-card ct-index"><header class="ct-index-toolbar"><div><h2>Sales orders</h2><span><?= count($chemtechOrders) ?> total</span></div><div class="ct-toolbar-actions"><label class="ct-search"><span>Search</span><input type="search" placeholder="Search orders" data-ct-table-filter="ct-order-table"></label><button class="ct-button primary" type="button" data-dialog-open="ct-order-dialog">Create order</button></div></header><?php if(!$chemtechOrders): ?><div class="ct-empty"><b>No sales orders</b><span>Orders will appear here after creation.</span><button class="ct-button" type="button" data-dialog-open="ct-order-dialog">Create first order</button></div><?php else: ?><div class="ct-table-wrap"><table class="ct-table" id="ct-order-table"><thead><tr><th>Order</th><th>Customer</th><th>Item</th><th>Tax</th><th>Total</th><th>Billing</th></tr></thead><tbody><?php foreach($chemtechOrders as $order): ?><tr><td><b><?= $e($order['order_number']) ?></b><small><?= $e(date('d M Y',strtotime((string)$order['created_at']))) ?></small></td><td><?= $e($order['customer_name']) ?></td><td><?= $e($order['product_name']) ?><small><?= number_format($order['quantity_milli']/1000,3).' '.$e($order['unit']) ?></small></td><td><?= $e($order['tax_type']) ?></td><td><?= chemtechMoney((int)$order['total_paise']) ?></td><td><span class="ct-status <?= $e($order['billing_status']) ?>"><?= $e(ucfirst($order['billing_status'])) ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>

        <?php elseif($chemtechPage==='invoices'): ?>
            <section class="ct-summary ct-summary-three"><div><span>Invoiced</span><strong><?= chemtechMoney($ctSales) ?></strong><small><?= count($chemtechInvoices) ?> invoices</small></div><div><span>Outstanding</span><strong><?= chemtechMoney($ctOutstanding) ?></strong><small><?= count($ctOpenInvoices) ?> open</small></div><div><span>Ready to bill</span><strong><?= chemtechMoney($ctUnbilledValue) ?></strong><small><?= count($ctUnbilled) ?> unbilled orders</small></div></section>
            <section class="ct-card ct-index"><header class="ct-index-toolbar"><div><h2>Invoice register</h2><span>Financial year <?= $e(chemtechFinancialYear()) ?></span></div><div class="ct-toolbar-actions"><label class="ct-search"><span>Search</span><input type="search" placeholder="Search invoices" data-ct-table-filter="ct-invoice-table"></label><button class="ct-button primary" type="button" data-dialog-open="ct-invoice-dialog" <?= !$ctUnbilled?'disabled':'' ?>>Generate invoice</button></div></header><?php if(!$chemtechInvoices): ?><div class="ct-empty"><b>No invoices generated</b><span>Create a sales order, then generate its GST invoice.</span></div><?php else: ?><div class="ct-table-wrap"><table class="ct-table" id="ct-invoice-table"><thead><tr><th>Invoice</th><th>Customer</th><th>Orders</th><th>Total</th><th>Balance</th><th>Status</th></tr></thead><tbody><?php foreach($chemtechInvoices as $invoice): $balance=max(0,(int)$invoice['total_paise']-(int)$invoice['paid_paise']); ?><tr><td><b><?= $e($invoice['invoice_number']) ?></b><small><?= $e($invoice['invoice_date'].' · due '.$invoice['due_date']) ?></small></td><td><?= $e($invoice['customer_name']) ?></td><td><?= count($invoice['order_ids']) ?></td><td><?= chemtechMoney((int)$invoice['total_paise']) ?></td><td><?= chemtechMoney($balance) ?></td><td><span class="ct-status <?= $e($invoice['status']) ?>"><?= $e(ucwords(str_replace('_',' ',$invoice['status']))) ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>

        <?php elseif($chemtechPage==='payments'): ?>
            <section class="ct-summary ct-summary-three"><div><span>Receivables</span><strong><?= chemtechMoney($ctOutstanding) ?></strong><small><?= count($ctOpenInvoices) ?> open invoices</small></div><div><span>Collected</span><strong><?= chemtechMoney($ctCollected) ?></strong><small><?= count($chemtechPayments) ?> payments</small></div><div><span>Collection rate</span><strong><?= $ctSales?round($ctCollected/$ctSales*100):0 ?>%</strong><small>Against invoiced sales</small></div></section>
            <section class="ct-card ct-index"><header class="ct-index-toolbar"><div><h2>Payment history</h2><span>Latest collections</span></div><div class="ct-toolbar-actions"><label class="ct-search"><span>Search</span><input type="search" placeholder="Search payments" data-ct-table-filter="ct-payment-table"></label><button class="ct-button primary" type="button" data-dialog-open="ct-payment-dialog" <?= !$ctOpenInvoices?'disabled':'' ?>>Record payment</button></div></header><?php if(!$chemtechPayments): ?><div class="ct-empty"><b>No payments recorded</b><span>Payments appear here after they are allocated to an invoice.</span></div><?php else: ?><div class="ct-table-wrap"><table class="ct-table" id="ct-payment-table"><thead><tr><th>Date</th><th>Customer</th><th>Invoice</th><th>Method</th><th>Reference</th><th>Amount</th></tr></thead><tbody><?php foreach($chemtechPayments as $payment): ?><tr><td><?= $e($payment['payment_date']) ?></td><td><b><?= $e($payment['customer_name']) ?></b></td><td><?= $e($payment['invoice_number']) ?></td><td><?= $e(ucfirst($payment['method'])) ?></td><td><?= $e($payment['reference']?:'—') ?></td><td><b><?= chemtechMoney((int)$payment['amount_paise']) ?></b></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>

        <?php elseif($chemtechPage==='inventory'): ?>
            <section class="ct-card ct-index"><header class="ct-index-toolbar"><div><h2>Stock overview</h2><span><?= count($ctLowStock) ?> products need attention</span></div><div class="ct-toolbar-actions"><label class="ct-search"><span>Search</span><input type="search" placeholder="Search inventory" data-ct-table-filter="ct-inventory-table"></label><a class="ct-button" href="?business=chemtech&amp;page=products">Manage products</a></div></header><div class="ct-table-wrap"><table class="ct-table" id="ct-inventory-table"><thead><tr><th>Product</th><th>Category</th><th>Available</th><th>Reorder level</th><th>Stock health</th></tr></thead><tbody><?php foreach($chemtechProducts as $product): $low=(int)$product['stock_milli']<=(int)$product['reorder_milli']; ?><tr><td><b><?= $e($product['name']) ?></b><small><?= $e($product['sku']) ?></small></td><td><?= $e($product['category']) ?></td><td><?= number_format($product['stock_milli']/1000,3).' '.$e($product['unit']) ?></td><td><?= number_format($product['reorder_milli']/1000,3).' '.$e($product['unit']) ?></td><td><span class="ct-status <?= $low?'warning':'ready' ?>"><?= $low?'Reorder required':'In stock' ?></span></td></tr><?php endforeach; ?></tbody></table></div></section>

        <?php elseif($chemtechPage==='settings'): ?>
            <form class="ct-settings-form" method="post"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>">
                <section class="ct-settings-row"><div><h2>Company identity</h2><p>Used throughout the workspace and future documents.</p></div><article class="ct-card"><div class="ct-brand-preview"><span><?= $e($chemtechSettings['short_name']) ?></span><div><b><?= $e($chemtechSettings['company_name']) ?></b><small>Workspace identity</small></div></div><div class="ct-form-grid two"><label>Workspace name<input name="company_name" value="<?= $e($chemtechSettings['company_name']) ?>" required></label><label>Icon letters<input name="short_name" maxlength="3" value="<?= $e($chemtechSettings['short_name']) ?>" required></label></div><label>Legal company name<input name="legal_name" value="<?= $e($chemtechSettings['legal_name']) ?>"></label></article></section>
                <section class="ct-settings-row"><div><h2>Tax registration</h2><p>State codes control CGST/SGST and IGST automatically.</p></div><article class="ct-card"><div class="ct-form-grid two"><label>GSTIN<input name="gstin" maxlength="15" value="<?= $e($chemtechSettings['gstin']) ?>"></label><label>PAN<input name="pan" value="<?= $e($chemtechSettings['pan']) ?>"></label><label>State<input name="state" value="<?= $e($chemtechSettings['state']) ?>"></label><label>GST state code<input name="state_code" maxlength="2" value="<?= $e($chemtechSettings['state_code']) ?>"></label></div><label>Registered address<textarea name="address" rows="3"><?= $e($chemtechSettings['address']) ?></textarea></label></article></section>
                <section class="ct-settings-row"><div><h2>Contact and bank</h2><p>Shown on invoices and commercial documents.</p></div><article class="ct-card"><div class="ct-form-grid two"><label>Phone<input name="phone" value="<?= $e($chemtechSettings['phone']) ?>"></label><label>Email<input type="email" name="email" value="<?= $e($chemtechSettings['email']) ?>"></label><label>Bank name<input name="bank_name" value="<?= $e($chemtechSettings['bank_name']) ?>"></label><label>Account number<input name="account_number" value="<?= $e($chemtechSettings['account_number']) ?>"></label><label>IFSC<input name="ifsc" value="<?= $e($chemtechSettings['ifsc']) ?>"></label><label>Invoice prefix<input name="invoice_prefix" maxlength="10" value="<?= $e($chemtechSettings['invoice_prefix']) ?>"></label></div></article></section>
                <div class="ct-settings-save"><button class="ct-button primary" name="save_chemtech_settings" value="1">Save settings</button></div>
            </form>

        <?php else: ?>
            <section class="ct-card ct-module"><div class="ct-module-badge">In development</div><h2><?= $e($ctTitle) ?></h2><p><?= $e($ctSubtitle) ?></p><div class="ct-module-flow"><?php $moduleSteps=['enquiries'=>['Capture enquiry','Schedule follow-up','Convert to quotation'],'quotations'=>['Build quotation','Share PDF','Convert to order'],'purchases'=>['Create supplier','Issue purchase order','Record goods receipt'],'dispatch'=>['Create delivery note','Add transport details','Record proof of delivery'],'reports'=>['Sales and GST','Outstanding ageing','Stock and margin'],'documents'=>['Invoices','Certificates','Supporting files']][$chemtechPage]??['Configure','Review','Complete']; foreach($moduleSteps as $step): ?><span><?= $e($step) ?></span><?php endforeach; ?></div><p class="ct-help">This module will connect to the existing customer → order → billing → payment workflow.</p></section>
        <?php endif; ?>
    </main>
</div>

<dialog class="ct-dialog" id="ct-customer-dialog"><form class="ct-dialog-panel" method="post"><header><div><span>Customers</span><h2>Add customer</h2></div><button type="button" data-dialog-close aria-label="Close">×</button></header><div class="ct-dialog-body"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><label>Business name<input name="name" required></label><div class="ct-form-grid two"><label>Contact person<input name="contact_person"></label><label>Phone<input name="phone" inputmode="tel"></label></div><label>Email<input type="email" name="email"></label><div class="ct-form-grid two"><label>GSTIN<input name="gstin" maxlength="15"></label><label>State code<input name="state_code" inputmode="numeric" maxlength="2" placeholder="27"></label><label>State<input name="state"></label><label>Billing cycle<select name="billing_cycle"><option value="per_order">Per order</option><option value="weekly">Weekly</option><option value="fortnightly">Fortnightly</option><option value="monthly">Monthly</option><option value="custom">Custom</option></select></label></div><label>Credit days<input type="number" name="credit_days" min="0" max="365" value="30"></label><label>Billing address<textarea name="address" rows="3"></textarea></label></div><footer><button class="ct-button" type="button" data-dialog-close>Cancel</button><button class="ct-button primary" name="add_chemtech_customer" value="1">Save customer</button></footer></form></dialog>

<dialog class="ct-dialog" id="ct-product-dialog"><form class="ct-dialog-panel" method="post"><header><div><span>Products</span><h2>Add chemical</h2></div><button type="button" data-dialog-close aria-label="Close">×</button></header><div class="ct-dialog-body"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><label>Product name<input name="name" required></label><div class="ct-form-grid two"><label>SKU<input name="sku" required></label><label>Category<input name="category"></label><label>HSN code<input name="hsn"></label><label>Unit<select name="unit"><option>kg</option><option>litre</option><option>drum</option><option>bag</option><option>unit</option></select></label><label>GST rate %<input type="number" name="gst_rate" min="0" max="50" step=".01" value="18"></label><label>Selling price<input type="number" name="sale_price" min="0" step=".01" required></label><label>Opening stock<input type="number" name="stock" min="0" step=".001"></label><label>Reorder level<input type="number" name="reorder_level" min="0" step=".001"></label></div></div><footer><button class="ct-button" type="button" data-dialog-close>Cancel</button><button class="ct-button primary" name="add_chemtech_product" value="1">Save product</button></footer></form></dialog>

<dialog class="ct-dialog" id="ct-order-dialog"><form class="ct-dialog-panel" method="post"><header><div><span>Orders</span><h2>Create sales order</h2></div><button type="button" data-dialog-close aria-label="Close">×</button></header><div class="ct-dialog-body"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><label>Customer<select name="customer_id" required><option value="">Choose customer…</option><?php foreach($chemtechCustomers as $customer): ?><option value="<?= $e($customer['id']) ?>"><?= $e($customer['name'].' · state '.$customer['state_code']) ?></option><?php endforeach; ?></select></label><label>Product<select name="product_id" required><option value="">Choose product…</option><?php foreach($chemtechProducts as $product): ?><option value="<?= $e($product['id']) ?>"><?= $e($product['name']) ?> · <?= number_format($product['stock_milli']/1000,3) ?> <?= $e($product['unit']) ?></option><?php endforeach; ?></select></label><div class="ct-form-grid two"><label>Quantity<input type="number" name="quantity" min=".001" step=".001" required></label><label>Unit price<input type="number" name="unit_price" min="0" step=".01" placeholder="Catalogue price"></label></div><div class="ct-inline-note">GST is selected from company and customer state codes. Confirming the order reduces available stock.</div></div><footer><button class="ct-button" type="button" data-dialog-close>Cancel</button><button class="ct-button primary" name="create_chemtech_order" value="1">Create order</button></footer></form></dialog>

<dialog class="ct-dialog" id="ct-invoice-dialog"><form class="ct-dialog-panel" method="post" data-ct-invoice-form><header><div><span>Billing</span><h2>Generate GST invoice</h2></div><button type="button" data-dialog-close aria-label="Close">×</button></header><div class="ct-dialog-body"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><div class="ct-inline-note">Select one or more unbilled orders from the same customer. An order cannot be billed twice.</div><?php if(!$ctUnbilled): ?><div class="ct-empty"><b>No unbilled orders</b></div><?php else: ?><div class="ct-select-list"><?php foreach($ctUnbilled as $order): ?><label data-customer="<?= $e($order['customer_id']) ?>"><input type="checkbox" name="order_ids[]" value="<?= $e($order['id']) ?>"><span><b><?= $e($order['customer_name'].' · '.$order['order_number']) ?></b><small><?= $e($order['product_name']) ?> · <?= chemtechMoney((int)$order['total_paise']) ?></small></span></label><?php endforeach; ?></div><?php endif; ?></div><footer><button class="ct-button" type="button" data-dialog-close>Cancel</button><button class="ct-button primary" name="create_chemtech_invoice" value="1" <?= !$ctUnbilled?'disabled':'' ?>>Generate invoice</button></footer></form></dialog>

<dialog class="ct-dialog" id="ct-payment-dialog"><form class="ct-dialog-panel" method="post"><header><div><span>Payments</span><h2>Record collection</h2></div><button type="button" data-dialog-close aria-label="Close">×</button></header><div class="ct-dialog-body"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><label>Invoice<select name="invoice_id" required><option value="">Choose invoice…</option><?php foreach($ctOpenInvoices as $invoice): ?><option value="<?= $e($invoice['id']) ?>"><?= $e($invoice['invoice_number'].' · '.$invoice['customer_name']) ?> · <?= chemtechMoney((int)$invoice['total_paise']-(int)$invoice['paid_paise']) ?></option><?php endforeach; ?></select></label><div class="ct-form-grid two"><label>Amount<input type="number" name="amount" min=".01" step=".01" required></label><label>Date<input type="date" name="payment_date" value="<?= date('Y-m-d') ?>" required></label><label>Method<select name="method"><option value="bank">Bank transfer</option><option value="upi">UPI</option><option value="cheque">Cheque</option><option value="cash">Cash</option></select></label><label>Reference<input name="reference"></label></div></div><footer><button class="ct-button" type="button" data-dialog-close>Cancel</button><button class="ct-button primary" name="record_chemtech_payment" value="1">Record payment</button></footer></form></dialog>
