<?php
$rangoliTitles=['dashboard'=>['Business Dashboard','Retail, dealer, stock and payment overview.'],'products'=>['Products','Choose products, then make your catalogue.'],'contacts'=>['Customers & Dealers','Keep buyers, dealers and marketing partners separate.'],'orders'=>['Orders','Create orders and follow every delivery.'],'payments'=>['Payments','See collected and pending order value.']];
[$rangoliTitle,$rangoliSubtitle]=$rangoliTitles[$rangoliPage];
$rangoliNav=['dashboard'=>'Dashboard','products'=>'Products','contacts'=>'People','orders'=>'Orders','payments'=>'Payments'];
$rangoliSales=array_sum(array_map(static fn($order)=>(float)($order['total']??0),$rangoliOrders));
$rangoliCollected=array_sum(array_map(static fn($order)=>(float)($order['paid']??0),$rangoliOrders));
$rangoliPending=max(0,$rangoliSales-$rangoliCollected);
$retailSales=array_sum(array_map(static fn($order)=>(($order['channel']??'')==='retail'?(float)($order['total']??0):0),$rangoliOrders));
$dealerSales=array_sum(array_map(static fn($order)=>(($order['channel']??'')==='dealer'?(float)($order['total']??0):0),$rangoliOrders));
$lowStockProducts=array_values(array_filter($rangoliProducts,static fn($product)=>(int)($product['stock']??0)<=(int)($product['low_stock']??3)));
?>
<div class="workspace-shell rangoli-workspace">
    <aside class="side-nav td-side-wide"><a class="side-logo ray-wordmark" href="./">RAY</a><nav><?php foreach($rangoliNav as $page=>$label): ?><a class="<?= $rangoliPage===$page?'active':'' ?>" href="?business=rangoli&page=<?= $page ?>"><small><?= $label ?></small></a><?php endforeach; ?></nav><button class="theme-toggle" data-theme-toggle type="button"><span>☼</span><small>Theme</small></button><a class="side-bottom" href="./">⌘</a></aside>
    <main class="td-dashboard">
        <nav class="desktop-menu"><a class="desktop-brand" href="./">RAY</a><div><?php foreach($rangoliNav as $page=>$label): ?><a class="<?= $rangoliPage===$page?'active':'' ?>" href="?business=rangoli&page=<?= $page ?>"><?= $label ?></a><?php endforeach; ?></div><button class="theme-toggle desktop-theme-toggle" data-theme-toggle type="button"><span>☼</span><small>Theme</small></button></nav>
        <header class="td-header"><div><a class="back-link" href="./">← All businesses</a><span class="eyebrow">WOOLLEN RANGOLI</span><h1><?= htmlspecialchars($rangoliTitle) ?></h1><p><?= htmlspecialchars($rangoliSubtitle) ?></p></div><div class="header-actions"><?php if($rangoliPage==='products'): ?><a class="primary-button button-link" href="?business=rangoli&amp;page=products&amp;new=1">＋ Add product</a><?php else: ?><a class="primary-button button-link" href="?business=rangoli&page=orders">＋ New order</a><?php endif; ?></div></header>
        <?php if($notice): ?><div class="td-notice"><?= htmlspecialchars($notice) ?></div><?php endif; ?>

        <?php if($rangoliPage==='dashboard'): ?>
            <section class="metric-grid"><a class="metric-card metric-link" href="?business=rangoli&page=orders"><span>Total sales</span><strong>₹<?= number_format($rangoliSales,0) ?></strong><small><?= count($rangoliOrders) ?> orders</small></a><a class="metric-card green metric-link" href="?business=rangoli&page=payments"><span>Collected</span><strong>₹<?= number_format($rangoliCollected,0) ?></strong><small>Received payments</small></a><a class="metric-card orange metric-link" href="?business=rangoli&page=payments"><span>Pending</span><strong>₹<?= number_format($rangoliPending,0) ?></strong><small>Still to collect</small></a><a class="metric-card purple metric-link" href="?business=rangoli&page=products"><span>Low stock</span><strong><?= count($lowStockProducts) ?></strong><small><?= count($rangoliProducts) ?> products saved</small></a></section>
            <section class="two-column"><article class="panel"><span class="eyebrow">SALES CHANNELS</span><h2>Retail and dealer</h2><div class="money-row"><span>Direct customers</span><strong>₹<?= number_format($retailSales,0) ?></strong></div><div class="money-row"><span>Dealers / stores</span><strong>₹<?= number_format($dealerSales,0) ?></strong></div></article><article class="panel"><span class="eyebrow">ATTENTION</span><h2>Low-stock products</h2><?php if(!$lowStockProducts): ?><p class="panel-note">No low-stock products.</p><?php endif; ?><?php foreach(array_slice($lowStockProducts,0,8) as $product): ?><div class="setting-row"><span><?= htmlspecialchars($product['name']) ?></span><strong><?= (int)$product['stock'] ?> left</strong></div><?php endforeach; ?></article></section>

        <?php elseif($rangoliPage==='products'): ?>
            <?php require __DIR__ . '/rangoli-products.php'; ?>

        <?php elseif($rangoliPage==='contacts'): ?>
            <section class="two-column"><article class="panel"><span class="eyebrow">NEW PERSON</span><h2>Add customer or dealer</h2><form class="stack-form" method="post"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf']) ?>"><label>Type</label><select name="type"><option value="customer">Direct customer</option><option value="dealer">Dealer / store</option><option value="partner">Marketing partner</option></select><label>Name</label><input name="name" maxlength="120" required><label>Mobile / WhatsApp</label><input name="phone" inputmode="tel"><label>Address</label><textarea name="address" rows="3"></textarea><label>Default discount % (optional)</label><input type="number" name="discount" min="0" max="100" step=".01"><button class="primary-button" name="add_contact" value="1">Save person</button></form></article><article class="panel"><span class="eyebrow">PEOPLE</span><h2>Saved contacts</h2><?php if(!$rangoliContacts): ?><p class="panel-note">No contacts yet.</p><?php endif; ?><?php foreach($rangoliContacts as $contact): $contactDigits=preg_replace('/\D+/','',(string)$contact['phone']); ?><div class="rangoli-contact"><div><strong><?= htmlspecialchars($contact['name']) ?></strong><small><?= ucfirst(htmlspecialchars($contact['type'])) ?><?= $contact['discount']?' · '.$contact['discount'].'% discount':'' ?></small></div><div class="lead-quick-actions"><?php if($contactDigits): ?><a href="tel:<?= htmlspecialchars($contact['phone']) ?>">Call</a><a class="whatsapp-action" href="https://wa.me/<?= htmlspecialchars($contactDigits) ?>" target="_blank" rel="noopener">WhatsApp</a><?php endif; ?></div></div><?php endforeach; ?></article></section>

        <?php elseif($rangoliPage==='orders'): ?>
            <section class="two-column"><article class="panel"><span class="eyebrow">NEW ORDER</span><h2>Create order</h2><?php if($rangoliProducts&&$rangoliContacts): ?><form class="stack-form" method="post"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf']) ?>"><label>Buyer</label><select name="contact_id" required><option value="">Choose customer/dealer…</option><?php foreach($rangoliContacts as $contact): if($contact['type']==='partner')continue; ?><option value="<?= htmlspecialchars($contact['id']) ?>"><?= htmlspecialchars($contact['name']) ?> — <?= $contact['type']==='dealer'?'Dealer price':'Retail price' ?></option><?php endforeach; ?></select><label>Product</label><select name="product_id" required><option value="">Choose product…</option><?php foreach($rangoliProducts as $product): ?><option value="<?= htmlspecialchars($product['id']) ?>"><?= htmlspecialchars($product['name']) ?> — <?= (int)$product['stock'] ?> available</option><?php endforeach; ?></select><label>Quantity</label><input type="number" name="quantity" min="1" value="1" required><label>Custom unit price (optional)</label><input type="number" name="unit_price" min="0" step=".01" placeholder="Uses retail/dealer price automatically"><label>Amount paid now</label><input type="number" name="paid" min="0" step=".01" value="0"><button class="primary-button" name="create_order" value="1">Create order</button></form><?php else: ?><p class="panel-note">Add at least one product and customer/dealer first.</p><?php endif; ?></article><article class="panel"><span class="eyebrow">WORKFLOW</span><h2>Update order</h2><?php if($rangoliOrders): ?><form class="stack-form" method="post"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf']) ?>"><label>Order</label><select name="order_id" required><option value="">Choose order…</option><?php foreach($rangoliOrders as $order): ?><option value="<?= htmlspecialchars($order['id']) ?>"><?= htmlspecialchars($order['contact_name'].' · '.$order['product_name']) ?></option><?php endforeach; ?></select><label>Status</label><select name="status"><?php foreach(['new','preparing','ready','dispatched','delivered','cancelled'] as $status): ?><option value="<?= $status ?>"><?= ucfirst($status) ?></option><?php endforeach; ?></select><label>Total amount received</label><input type="number" name="paid" min="0" step=".01"><button class="small-button" name="update_order" value="1">Update order</button></form><?php else: ?><p class="panel-note">No orders yet.</p><?php endif; ?></article></section>
            <section class="panel page-panel"><div class="panel-heading"><div><span class="eyebrow">ORDER BOOK</span><h2>Recent orders</h2></div><span class="soft-badge"><?= count($rangoliOrders) ?> orders</span></div><?php if(!$rangoliOrders): ?><div class="empty-state compact"><h3>No orders yet</h3></div><?php else: ?><div class="lead-table-wrap"><table class="lead-table"><thead><tr><th>Buyer</th><th>Product</th><th>Channel</th><th>Total</th><th>Pending</th><th>Status</th><th>Contact</th></tr></thead><tbody><?php foreach($rangoliOrders as $order): $orderDigits=preg_replace('/\D+/','',(string)($order['contact_phone']??'')); ?><tr><td><strong><?= htmlspecialchars($order['contact_name']) ?></strong><small><?= date('d M Y',strtotime($order['created_at'])) ?></small></td><td><?= htmlspecialchars($order['product_name']) ?><small><?= (int)$order['quantity'] ?> × ₹<?= number_format((float)$order['unit_price'],0) ?></small></td><td><?= ucfirst(htmlspecialchars($order['channel'])) ?></td><td>₹<?= number_format((float)$order['total'],0) ?></td><td>₹<?= number_format(max(0,(float)$order['total']-(float)$order['paid']),0) ?></td><td><span class="lead-status <?= htmlspecialchars($order['status']) ?>"><?= ucfirst(htmlspecialchars($order['status'])) ?></span></td><td><?php if($orderDigits): ?><a class="call-link" href="https://wa.me/<?= htmlspecialchars($orderDigits) ?>" target="_blank" rel="noopener">WhatsApp</a><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>

        <?php else: ?>
            <section class="metric-grid"><article class="metric-card"><span>Total order value</span><strong>₹<?= number_format($rangoliSales,0) ?></strong><small>All channels</small></article><article class="metric-card green"><span>Collected</span><strong>₹<?= number_format($rangoliCollected,0) ?></strong><small><?= $rangoliSales?round($rangoliCollected/$rangoliSales*100):0 ?>% collection rate</small></article><article class="metric-card orange"><span>Pending</span><strong>₹<?= number_format($rangoliPending,0) ?></strong><small>Outstanding</small></article><article class="metric-card purple"><span>Orders</span><strong><?= count($rangoliOrders) ?></strong><small><?= count(array_filter($rangoliOrders,static fn($order)=>($order['status']??'')==='delivered')) ?> delivered</small></article></section><section class="panel page-panel"><div class="panel-heading"><div><span class="eyebrow">OUTSTANDING</span><h2>Pending payments</h2></div></div><?php $pendingOrders=array_filter($rangoliOrders,static fn($order)=>(float)$order['paid']<(float)$order['total']); if(!$pendingOrders): ?><div class="empty-state compact"><h3>No pending payments</h3></div><?php else: ?><?php foreach($pendingOrders as $order): ?><div class="money-row pending"><span><?= htmlspecialchars($order['contact_name'].' · '.$order['product_name']) ?></span><strong>₹<?= number_format((float)$order['total']-(float)$order['paid'],0) ?></strong></div><?php endforeach; ?><?php endif; ?></section>
        <?php endif; ?>
    </main>
</div>
