<?php
declare(strict_types=1);
$cid=$user['company_id'];
$period=$inventoryPeriod??'daily';$periodStart=match($period){'yearly'=>date('Y-01-01'),'monthly'=>date('Y-m-01'),default=>date('Y-m-d')};$periodLabel=match($period){'yearly'=>'This year','monthly'=>'This month',default=>'Today'};
$visibleProjectIds=array_column($projects,'id');$scopePlaceholders=$visibleProjectIds?implode(',',array_fill(0,count($visibleProjectIds),'?')):"''";
$inventory=phase_rows($db,'SELECT m.*,p.name project_name,p.code project_code,m.opening_stock+COALESCE(SUM(CASE WHEN t.transaction_type IN("received","returned","adjustment") THEN t.quantity WHEN t.transaction_type IN("issued","wasted","transferred") THEN -t.quantity ELSE 0 END),0) balance FROM materials m JOIN projects p ON p.id=m.project_id LEFT JOIN material_transactions t ON t.material_id=m.id WHERE m.company_id=? AND m.project_id IN ('.$scopePlaceholders.') GROUP BY m.id ORDER BY p.name,m.category,m.name',array_merge([$cid],$visibleProjectIds));
$transfers=phase_rows($db,'SELECT mt.*,sp.name source_site,dp.name destination_site,m.name material_name,u.name created_name FROM material_transfers mt JOIN projects sp ON sp.id=mt.source_project_id JOIN projects dp ON dp.id=mt.destination_project_id JOIN materials m ON m.id=mt.source_material_id LEFT JOIN users u ON u.id=mt.created_by WHERE mt.company_id=? AND (mt.source_project_id IN ('.$scopePlaceholders.') OR mt.destination_project_id IN ('.$scopePlaceholders.')) ORDER BY mt.transfer_date DESC,mt.created_at DESC LIMIT 100',array_merge([$cid],$visibleProjectIds,$visibleProjectIds));
$periodTransfers=array_values(array_filter($transfers,fn($t)=>$t['transfer_date']>=$periodStart));$activity=phase_one($db,'SELECT COALESCE(SUM(CASE WHEN transaction_type IN("received","returned") THEN quantity ELSE 0 END),0) received,COALESCE(SUM(CASE WHEN transaction_type IN("issued","wasted") THEN quantity ELSE 0 END),0) used_qty,COALESCE(SUM(CASE WHEN transaction_type="transferred" THEN quantity ELSE 0 END),0) transferred FROM material_transactions WHERE company_id=? AND project_id IN ('.$scopePlaceholders.') AND transaction_date>=?',array_merge([$cid],$visibleProjectIds,[$periodStart]));
$totalBalance=array_sum(array_map(fn($m)=>(float)$m['balance'],$inventory));$totalExcess=array_sum(array_map(fn($m)=>max(0,(float)$m['balance']-(float)$m['minimum_stock']),$inventory));$lowStock=array_values(array_filter($inventory,fn($m)=>(float)$m['balance']<=(float)$m['minimum_stock']));$excessItems=array_values(array_filter($inventory,fn($m)=>(float)$m['balance']>(float)$m['minimum_stock']));
$search=trim((string)($_GET['q']??''));$siteFilter=trim((string)($_GET['site']??''));$categoryFilter=trim((string)($_GET['category']??''));$filteredInventory=array_values(array_filter($inventory,function($m)use($search,$siteFilter,$categoryFilter){return(!$siteFilter||$m['project_id']===$siteFilter)&&(!$categoryFilter||$m['category']===$categoryFilter)&&(!$search||stripos($m['name'].' '.$m['project_name'].' '.$m['category'],$search)!==false);}));$categories=array_values(array_unique(array_filter(array_column($inventory,'category'))));sort($categories);
$sourceProject=(string)($_GET['project']??($projects[0]['id']??''));$sourceMaterials=array_values(array_filter($excessItems,fn($m)=>$m['project_id']===$sourceProject));
?>
<?php if($page==='dashboard'):?>
<section class="page-title inventory-title"><div><span class="eyebrow"><?=e(strtoupper($periodLabel))?> · MATERIAL CONTROL</span><h1>Inventory Dashboard</h1><p class="muted">Daily updates with monthly and yearly review.</p></div><div class="page-title-actions"><form class="page-period" method="get"><input type="hidden" name="page" value="dashboard"><span>Period</span><select name="period" onchange="this.form.submit()"><option value="daily" <?=$period==='daily'?'selected':''?>>Daily</option><option value="monthly" <?=$period==='monthly'?'selected':''?>>Monthly</option><option value="yearly" <?=$period==='yearly'?'selected':''?>>Yearly</option></select></form><a class="button" href="?page=transfers">Transfer Material</a></div></section>
<section class="cards inventory-kpis"><article class="card"><span>Material received</span><strong><?=number_format((float)($activity['received']??0),2)?></strong><small class="muted"><?=e($periodLabel)?></small></article><article class="card"><span>Material used / wasted</span><strong><?=number_format((float)($activity['used_qty']??0),2)?></strong><small class="muted"><?=e($periodLabel)?></small></article><article class="card"><span>Transferred out</span><strong><?=number_format((float)($activity['transferred']??0),2)?></strong><small class="muted"><?=e($periodLabel)?></small></article><article class="card excess-card"><span>Available excess now</span><strong><?=number_format($totalExcess,2)?></strong><small>Ready to transfer</small></article></section>
<div class="inventory-dashboard-grid"><section class="panel"><div class="panel-head"><div><h2>Excess material ready to move</h2><p class="muted">Stock above the site's minimum requirement.</p></div><a href="?page=transfers">View all</a></div><?php foreach(array_slice($excessItems,0,8) as $m):?><div class="stock-alert excess"><div><b><?=e($m['name'])?></b><small><?=e($m['project_name'])?> · Balance <?=e((string)$m['balance'].' '.$m['unit'])?></small></div><strong><?=number_format(max(0,(float)$m['balance']-(float)$m['minimum_stock']),2)?> <?=e($m['unit'])?></strong></div><?php endforeach;?><?php if(!$excessItems):?><p class="empty-cell">No excess stock currently available.</p><?php endif;?></section><section class="panel"><div class="panel-head"><div><h2>Low stock</h2><p class="muted">Items at or below minimum level.</p></div></div><?php foreach(array_slice($lowStock,0,8) as $m):?><div class="stock-alert low"><div><b><?=e($m['name'])?></b><small><?=e($m['project_name'])?></small></div><strong><?=e((string)$m['balance'].' '.$m['unit'])?></strong></div><?php endforeach;?><?php if(!$lowStock):?><p class="empty-cell">No low-stock items.</p><?php endif;?></section></div>
<section class="panel recent-transfers"><div class="panel-head"><div><h2><?=e($periodLabel)?> site transfers</h2><p class="muted">Material movements for the selected period.</p></div><a href="?page=transfers">Transfer history</a></div><?=phase_table(['Date','Material','From','To','Quantity','Moved by'],array_map(fn($t)=>[e($t['transfer_date']),e($t['material_name']),e($t['source_site']),e($t['destination_site']),e($t['quantity'].' '.$t['unit']),e($t['created_name']?:'—')],array_slice($periodTransfers,0,10)))?></section>
<?php elseif($page==='inventory'):?>
<section class="page-title inventory-title"><div><span class="eyebrow">ALL SITES</span><h1>All Inventory</h1><p class="muted">One searchable view of materials across every construction site.</p></div><a class="button" href="?page=materials">Add Material</a></section>
<form class="inventory-filters" method="get"><input type="hidden" name="page" value="inventory"><input name="q" value="<?=e($search)?>" placeholder="Search material, site or category"><select name="site"><option value="">All sites</option><?php foreach($projects as $p):?><option value="<?=e($p['id'])?>" <?=$siteFilter===$p['id']?'selected':''?>><?=e($p['name'])?></option><?php endforeach;?></select><select name="category"><option value="">All categories</option><?php foreach($categories as $category):?><option <?=$categoryFilter===$category?'selected':''?>><?=e($category)?></option><?php endforeach;?></select><button>Filter</button></form>
<?=phase_table(['Site','Category','Material','Unit','Opening','Balance','Minimum','Excess','Status'],array_map(function($m){$excess=max(0,(float)$m['balance']-(float)$m['minimum_stock']);return[e($m['project_name']),e($m['category']),e($m['name']),e($m['unit']),e((string)$m['opening_stock']),e((string)$m['balance']),e((string)$m['minimum_stock']),$excess>0?'<strong class="excess-number">'.e(number_format($excess,2)).'</strong>':'—',(float)$m['balance']<=(float)$m['minimum_stock']?'<span class="pill bad">Low</span>':($excess>0?'<span class="pill excess-pill">Excess</span>':'<span class="pill good">Balanced</span>')];},$filteredInventory))?>
<?php elseif($page==='transfers'):?>
<section class="page-title inventory-title"><div><span class="eyebrow">STOCK MOVEMENT</span><h1>Excess & Transfers</h1><p class="muted">Move only surplus material while protecting each site's minimum stock.</p></div></section>
<div class="transfer-layout"><form class="form-card transfer-form" method="get"><h2>Choose source site</h2><input type="hidden" name="page" value="transfers"><label class="field">Source site<select name="project" onchange="this.form.submit()"><?php foreach($projects as $p):?><option value="<?=e($p['id'])?>" <?=$sourceProject===$p['id']?'selected':''?>><?=e($p['name'])?></option><?php endforeach;?></select></label></form><form class="form-card transfer-form" method="post"><h2>Transfer excess material</h2><?=phase_hidden('material_transfer','transfers',$sourceProject)?><label class="field">Excess material<select name="material_id" required><option value="">Select available material</option><?php foreach($sourceMaterials as $m):$available=max(0,(float)$m['balance']-(float)$m['minimum_stock']);?><option value="<?=e($m['id'])?>"><?=e($m['name'].' · '.number_format($available,2).' '.$m['unit'].' excess')?></option><?php endforeach;?></select></label><label class="field">Destination site<select name="destination_project_id" required><option value="">Select destination</option><?php foreach($projects as $p):if($p['id']===$sourceProject)continue;?><option value="<?=e($p['id'])?>"><?=e($p['name'])?></option><?php endforeach;?></select></label><div class="form-grid"><label class="field">Quantity<input type="number" min="0.001" step="0.001" name="quantity" required></label><label class="field">Transfer date<input type="date" name="transaction_date" value="<?=date('Y-m-d')?>" required></label></div><label class="field">Notes<input name="notes" placeholder="Vehicle, challan or reason"></label><button class="button">Complete Transfer</button><?php if(!$sourceMaterials):?><p class="form-hint">This site currently has no material above its minimum stock level.</p><?php endif;?></form></div>
<section class="panel"><div class="panel-head"><div><h2>Transfer history</h2><p class="muted">Every completed site-to-site movement.</p></div></div><?=phase_table(['Date','Material','Source site','Destination site','Quantity','Notes','Moved by'],array_map(fn($t)=>[e($t['transfer_date']),e($t['material_name']),e($t['source_site']),e($t['destination_site']),e($t['quantity'].' '.$t['unit']),e($t['notes']?:'—'),e($t['created_name']?:'—')],$transfers))?></section>
<?php else:?>
<section class="page-title inventory-title"><div><span class="eyebrow"><?=e(strtoupper($periodLabel))?> SUMMARY</span><h1>Inventory Reports</h1><p class="muted">A clean operational summary without charts.</p></div><div class="page-title-actions"><form class="page-period" method="get"><input type="hidden" name="page" value="reports"><span>Period</span><select name="period" onchange="this.form.submit()"><option value="daily" <?=$period==='daily'?'selected':''?>>Daily</option><option value="monthly" <?=$period==='monthly'?'selected':''?>>Monthly</option><option value="yearly" <?=$period==='yearly'?'selected':''?>>Yearly</option></select></form></div></section>
<?php $groupFormat=match($period){'yearly'=>'%Y','monthly'=>'%b %Y',default=>'%d %b %Y'};$reportRows=phase_rows($db,'SELECT DATE_FORMAT(t.transaction_date,"'.$groupFormat.'") report_period,p.name site_name,SUM(CASE WHEN t.transaction_type IN("received","returned") THEN t.quantity ELSE 0 END) received,SUM(CASE WHEN t.transaction_type IN("issued","wasted") THEN t.quantity ELSE 0 END) used_qty,SUM(CASE WHEN t.transaction_type="transferred" THEN t.quantity ELSE 0 END) transferred FROM material_transactions t JOIN projects p ON p.id=t.project_id WHERE t.company_id=? AND t.project_id IN ('.$scopePlaceholders.') AND t.transaction_date>=? GROUP BY report_period,p.id ORDER BY MIN(t.transaction_date) DESC,p.name',array_merge([$cid],$visibleProjectIds,[$periodStart]));?>
<?=phase_table([ucfirst($period),'Site','Received','Used / Wasted','Transferred out'],array_map(fn($r)=>[e($r['report_period']),e($r['site_name']),e(number_format((float)$r['received'],2)),e(number_format((float)$r['used_qty'],2)),e(number_format((float)$r['transferred'],2))],$reportRows))?>
<?php endif;?>
