<?php
declare(strict_types=1);
function ensure_phase4(PDO $db):void{
 $tables=[
 'customers'=>'CREATE TABLE IF NOT EXISTS customers(id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,lead_id CHAR(26) NULL,name VARCHAR(160) NOT NULL,phone VARCHAR(30) NULL,email VARCHAR(190) NULL,address VARCHAR(255) NULL,pan VARCHAR(20) NULL,created_by CHAR(26) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_customer_company(company_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
 'brokers'=>'CREATE TABLE IF NOT EXISTS brokers(id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,name VARCHAR(160) NOT NULL,company_name VARCHAR(160) NULL,phone VARCHAR(30) NULL,email VARCHAR(190) NULL,rera_number VARCHAR(80) NULL,commission_type ENUM("percentage","fixed") DEFAULT "percentage",commission_value DECIMAL(12,2) DEFAULT 0,status ENUM("active","inactive") DEFAULT "active",created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_broker_company(company_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
 'units'=>'CREATE TABLE IF NOT EXISTS units(id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,project_id CHAR(26) NOT NULL,tower VARCHAR(80) NULL,wing VARCHAR(80) NULL,floor_label VARCHAR(40) NULL,unit_number VARCHAR(50) NOT NULL,property_type VARCHAR(60) NOT NULL,carpet_area DECIMAL(12,2) DEFAULT 0,builtup_area DECIMAL(12,2) DEFAULT 0,base_price DECIMAL(16,2) DEFAULT 0,floor_rise DECIMAL(16,2) DEFAULT 0,parking_charges DECIMAL(16,2) DEFAULT 0,other_charges DECIMAL(16,2) DEFAULT 0,final_price DECIMAL(16,2) DEFAULT 0,status ENUM("available","hold","reserved","booked","sold","blocked","cancelled") DEFAULT "available",created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_unit(project_id,unit_number),KEY ix_unit_company_status(company_id,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
 'bookings'=>'CREATE TABLE IF NOT EXISTS bookings(id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,project_id CHAR(26) NOT NULL,unit_id CHAR(26) NOT NULL,customer_id CHAR(26) NOT NULL,lead_id CHAR(26) NULL,broker_id CHAR(26) NULL,base_price DECIMAL(16,2) NOT NULL,discount DECIMAL(16,2) DEFAULT 0,final_price DECIMAL(16,2) NOT NULL,booking_amount DECIMAL(16,2) DEFAULT 0,booking_date DATE NOT NULL,sales_executive_id CHAR(26) NULL,payment_plan VARCHAR(160) NULL,notes VARCHAR(255) NULL,status ENUM("active","cancelled","completed") DEFAULT "active",created_by CHAR(26) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_booking_company(company_id,status),KEY ix_booking_unit(unit_id,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
 'payment_schedules'=>'CREATE TABLE IF NOT EXISTS payment_schedules(id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,booking_id CHAR(26) NOT NULL,stage_name VARCHAR(160) NOT NULL,due_date DATE NOT NULL,amount_due DECIMAL(16,2) NOT NULL,amount_received DECIMAL(16,2) DEFAULT 0,status ENUM("upcoming","due","partially_paid","paid","overdue") DEFAULT "upcoming",created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_schedule_company_due(company_id,due_date,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
 'payments'=>'CREATE TABLE IF NOT EXISTS payments(id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,booking_id CHAR(26) NOT NULL,payment_schedule_id CHAR(26) NOT NULL,amount DECIMAL(16,2) NOT NULL,payment_date DATE NOT NULL,payment_method VARCHAR(60) NULL,reference_no VARCHAR(100) NULL,notes VARCHAR(255) NULL,received_by CHAR(26) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_payment_company_date(company_id,payment_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
 'broker_commissions'=>'CREATE TABLE IF NOT EXISTS broker_commissions(id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,broker_id CHAR(26) NOT NULL,booking_id CHAR(26) NOT NULL,amount_earned DECIMAL(16,2) DEFAULT 0,amount_paid DECIMAL(16,2) DEFAULT 0,status ENUM("pending","partially_paid","paid") DEFAULT "pending",created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_commission_broker(broker_id,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'];
 foreach($tables as $sql)$db->exec($sql);
 foreach(['units.view','units.manage','customers.view','customers.manage','bookings.view','bookings.manage','collections.view','collections.manage','brokers.view','brokers.manage'] as $key){$q=$db->prepare('SELECT id FROM permissions WHERE permission_key=?');$q->execute([$key]);$pid=$q->fetchColumn();if(!$pid){$pid=id26();[$m,$a]=explode('.',$key,2);$db->prepare('INSERT INTO permissions(id,module_name,action_name,permission_key) VALUES(?,?,?,?)')->execute([$pid,$m,$a,$key]);}$db->prepare('INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT id,? FROM roles WHERE code="OWNER"')->execute([$pid]);}
}
function phase4_action(PDO $db,array $user):?array{
 $a=(string)($_POST['phase4_action']??'');if(!$a)return null;$c=$user['company_id'];$page=field('return_page')?:'units';$project=field('project_id');if($project&&!scoped_project($db,$user,$project))return['error'=>'Choose a valid project.'];$need=function($p)use($db,$user,$project){if(!can($db,$user,$p,$project?:null)){http_response_code(403);exit('Forbidden');}};
 try{
  if($a==='unit_add'){$need('units.manage');$base=max(0,(float)($_POST['base_price']??0));$rise=max(0,(float)($_POST['floor_rise']??0));$parking=max(0,(float)($_POST['parking_charges']??0));$other=max(0,(float)($_POST['other_charges']??0));$final=$base+$rise+$parking+$other;$db->prepare('INSERT INTO units(id,company_id,project_id,tower,wing,floor_label,unit_number,property_type,carpet_area,builtup_area,base_price,floor_rise,parking_charges,other_charges,final_price,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([id26(),$c,$project,field('tower'),field('wing'),field('floor_label'),field('unit_number'),field('property_type'),max(0,(float)($_POST['carpet_area']??0)),max(0,(float)($_POST['builtup_area']??0)),$base,$rise,$parking,$other,$final,field('status')?:'available']);}
  elseif($a==='unit_status'){$need('units.manage');$status=field('status');if(!in_array($status,['available','hold','reserved','blocked','cancelled'],true))return['error'=>'Booked or sold units can only change through booking workflows.'];$db->prepare('UPDATE units SET status=? WHERE id=? AND company_id=? AND project_id=? AND status NOT IN("booked","sold")')->execute([$status,field('unit_id'),$c,$project]);}
  elseif($a==='customer_add'){$need('customers.manage');$db->prepare('INSERT INTO customers(id,company_id,lead_id,name,phone,email,address,pan,created_by) VALUES(?,?,?,?,?,?,?,?,?)')->execute([id26(),$c,field('lead_id')?:null,field('name'),field('phone'),strtolower(field('email')),field('address'),strtoupper(field('pan')),$user['id']]);}
  elseif($a==='booking_add'){$need('bookings.manage');$db->beginTransaction();$uid=field('unit_id');$q=$db->prepare('SELECT * FROM units WHERE id=? AND company_id=? AND project_id=? FOR UPDATE');$q->execute([$uid,$c,$project]);$unit=$q->fetch();if(!$unit||!in_array($unit['status'],['available','hold','reserved'],true))throw new DomainException('This unit has already been booked or is unavailable.');$customer=field('customer_id');$qc=$db->prepare('SELECT 1 FROM customers WHERE id=? AND company_id=?');$qc->execute([$customer,$c]);if(!$qc->fetchColumn())throw new DomainException('Choose a valid customer.');$discount=max(0,(float)($_POST['discount']??0));$final=max(0,(float)$unit['final_price']-$discount);$bid=id26();$db->prepare('INSERT INTO bookings(id,company_id,project_id,unit_id,customer_id,lead_id,broker_id,base_price,discount,final_price,booking_amount,booking_date,sales_executive_id,payment_plan,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$bid,$c,$project,$uid,$customer,field('lead_id')?:null,field('broker_id')?:null,$unit['final_price'],$discount,$final,max(0,(float)($_POST['booking_amount']??0)),field('booking_date')?:date('Y-m-d'),field('sales_executive_id')?:null,field('payment_plan'),field('notes'),$user['id']]);$db->prepare('UPDATE units SET status="booked" WHERE id=?')->execute([$uid]);if(field('broker_id')){$broker=field('broker_id');$bq=$db->prepare('SELECT commission_type,commission_value FROM brokers WHERE id=? AND company_id=?');$bq->execute([$broker,$c]);if($br=$bq->fetch()){$earned=$br['commission_type']==='percentage'?$final*(float)$br['commission_value']/100:(float)$br['commission_value'];$db->prepare('INSERT INTO broker_commissions(id,company_id,broker_id,booking_id,amount_earned) VALUES(?,?,?,?,?)')->execute([id26(),$c,$broker,$bid,$earned]);}}$db->commit();}
  elseif($a==='schedule_add'){$need('collections.manage');$bid=field('booking_id');$q=$db->prepare('SELECT 1 FROM bookings WHERE id=? AND company_id=?');$q->execute([$bid,$c]);if(!$q->fetchColumn())return['error'=>'Choose a valid booking.'];$due=field('due_date');$status=$due<date('Y-m-d')?'overdue':($due===date('Y-m-d')?'due':'upcoming');$db->prepare('INSERT INTO payment_schedules(id,company_id,booking_id,stage_name,due_date,amount_due,status) VALUES(?,?,?,?,?,?,?)')->execute([id26(),$c,$bid,field('stage_name'),$due,max(0,(float)($_POST['amount_due']??0)),$status]);}
  elseif($a==='payment_add'){$need('collections.manage');$db->beginTransaction();$sid=field('schedule_id');$q=$db->prepare('SELECT * FROM payment_schedules WHERE id=? AND company_id=? FOR UPDATE');$q->execute([$sid,$c]);$s=$q->fetch();if(!$s)throw new DomainException('Choose a valid payment schedule.');$amount=max(0,(float)($_POST['amount']??0));$remaining=max(0,(float)$s['amount_due']-(float)$s['amount_received']);if($amount<=0||$amount>$remaining)throw new DomainException('Payment amount must not exceed the outstanding balance.');$db->prepare('INSERT INTO payments(id,company_id,booking_id,payment_schedule_id,amount,payment_date,payment_method,reference_no,notes,received_by) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([id26(),$c,$s['booking_id'],$sid,$amount,field('payment_date')?:date('Y-m-d'),field('payment_method'),field('reference_no'),field('notes'),$user['id']]);$received=(float)$s['amount_received']+$amount;$status=$received>=(float)$s['amount_due']?'paid':'partially_paid';$db->prepare('UPDATE payment_schedules SET amount_received=?,status=? WHERE id=?')->execute([$received,$status,$sid]);$db->commit();}
  elseif($a==='broker_add'){$need('brokers.manage');$db->prepare('INSERT INTO brokers(id,company_id,name,company_name,phone,email,rera_number,commission_type,commission_value) VALUES(?,?,?,?,?,?,?,?,?)')->execute([id26(),$c,field('name'),field('company_name'),field('phone'),field('email'),field('rera_number'),field('commission_type'),max(0,(float)($_POST['commission_value']??0))]);}
  else return['error'=>'Unknown action.'];audit($db,$user,strtok($a,'_'),'create');$_SESSION['notice']='Saved successfully.';go('./?page='.rawurlencode($page));
 }catch(DomainException $e){if($db->inTransaction())$db->rollBack();return['error'=>$e->getMessage()];}catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log($e->getMessage());return['error'=>'The record could not be saved. Check the required fields.'];}
}
