<?php
declare(strict_types=1);
function ensure_phase56(PDO $db):void{
 $db->exec('CREATE TABLE IF NOT EXISTS notifications(id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,user_id CHAR(26) NULL,project_id CHAR(26) NULL,type VARCHAR(80) NOT NULL,title VARCHAR(190) NOT NULL,message VARCHAR(255) NOT NULL,record_key VARCHAR(190) NULL,is_read TINYINT(1) DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_notification(company_id,record_key),KEY ix_notify_user(company_id,user_id,is_read,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
 $db->exec('CREATE TABLE IF NOT EXISTS approvals(id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,project_id CHAR(26) NULL,module_name VARCHAR(80) NOT NULL,record_id CHAR(26) NOT NULL,title VARCHAR(190) NOT NULL,amount DECIMAL(16,2) DEFAULT 0,status ENUM("pending","approved","rejected","cancelled") DEFAULT "pending",requested_by CHAR(26) NULL,approver_id CHAR(26) NULL,decision_notes VARCHAR(255) NULL,decided_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_approval_record(company_id,module_name,record_id),KEY ix_approval_company(company_id,status,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
 $db->exec('CREATE TABLE IF NOT EXISTS schema_migrations(version VARCHAR(80) PRIMARY KEY,description VARCHAR(255) NOT NULL,applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
 $db->exec('CREATE TABLE IF NOT EXISTS login_attempts(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) NOT NULL,ip_address VARCHAR(45) NOT NULL,succeeded TINYINT(1) DEFAULT 0,attempted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_login_guard(email,ip_address,attempted_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
 $db->exec("INSERT IGNORE INTO schema_migrations(version,description) VALUES('001-foundation','Authentication, companies, permissions and projects'),('002-construction-sales','Construction and sales CRM modules'),('003-property-sales','Units, bookings and collections'),('004-management-production','Management and production hardening')");
 foreach(['reports.view','reports.export','notifications.view','approvals.view','approvals.manage','audit.view','system.view'] as $key){$q=$db->prepare('SELECT id FROM permissions WHERE permission_key=?');$q->execute([$key]);$pid=$q->fetchColumn();if(!$pid){$pid=id26();[$m,$a]=explode('.',$key,2);$db->prepare('INSERT INTO permissions(id,module_name,action_name,permission_key) VALUES(?,?,?,?)')->execute([$pid,$m,$a,$key]);}$db->prepare('INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT id,? FROM roles WHERE code="OWNER"')->execute([$pid]);}
 $db->exec('UPDATE payment_schedules SET status="overdue" WHERE due_date<CURDATE() AND amount_received<amount_due AND status NOT IN("paid")');
 $db->exec('UPDATE payment_schedules SET status="due" WHERE due_date=CURDATE() AND amount_received<amount_due AND status="upcoming"');
}
function sync_management(PDO $db,array $user):void{
 $c=$user['company_id'];
 $db->prepare('INSERT IGNORE INTO approvals(id,company_id,project_id,module_name,record_id,title,amount,requested_by) SELECT LEFT(REPLACE(UUID(),"-",""),26),company_id,project_id,"purchase_request",id,CONCAT("Purchase request: ",COALESCE(reason,"Material requirement")),0,requested_by FROM purchase_requests WHERE company_id=? AND status="pending"')->execute([$c]);
 $db->prepare('INSERT IGNORE INTO approvals(id,company_id,project_id,module_name,record_id,title,amount,requested_by) SELECT LEFT(REPLACE(UUID(),"-",""),26),company_id,project_id,"expense",id,CONCAT("Expense: ",category),amount+tax,created_by FROM expenses WHERE company_id=? AND status="pending"')->execute([$c]);
 $db->prepare('INSERT IGNORE INTO notifications(id,company_id,project_id,type,title,message,record_key) SELECT LEFT(REPLACE(UUID(),"-",""),26),m.company_id,m.project_id,"low_stock","Low material stock",CONCAT(m.name," is at ",ROUND(m.opening_stock+COALESCE((SELECT SUM(CASE WHEN t.transaction_type IN("received","returned","adjustment") THEN t.quantity WHEN t.transaction_type IN("issued","wasted","transferred") THEN -t.quantity ELSE 0 END) FROM material_transactions t WHERE t.material_id=m.id),0),2)," ",m.unit),CONCAT("stock:",m.id) FROM materials m WHERE m.company_id=? AND m.opening_stock+COALESCE((SELECT SUM(CASE WHEN t.transaction_type IN("received","returned","adjustment") THEN t.quantity WHEN t.transaction_type IN("issued","wasted","transferred") THEN -t.quantity ELSE 0 END) FROM material_transactions t WHERE t.material_id=m.id),0)<=m.minimum_stock')->execute([$c]);
 $db->prepare('INSERT IGNORE INTO notifications(id,company_id,type,title,message,record_key) SELECT LEFT(REPLACE(UUID(),"-",""),26),company_id,"overdue_collection","Customer payment overdue",CONCAT(stage_name," is overdue by ",DATEDIFF(CURDATE(),due_date)," days"),CONCAT("collection:",id) FROM payment_schedules WHERE company_id=? AND status="overdue"')->execute([$c]);
 $db->prepare('INSERT IGNORE INTO notifications(id,company_id,type,title,message,record_key) SELECT LEFT(REPLACE(UUID(),"-",""),26),f.company_id,"followup_due","Lead follow-up overdue",CONCAT("Follow-up is overdue for ",l.name),CONCAT("followup:",f.id) FROM followups f JOIN leads l ON l.id=f.lead_id WHERE f.company_id=? AND f.status="pending" AND f.followup_at<NOW()')->execute([$c]);
}
function phase56_action(PDO $db,array $user):?array{$a=field('phase56_action');if(!$a)return null;$c=$user['company_id'];try{if($a==='notification_read'){if(!can($db,$user,'notifications.view'))exit('Forbidden');$db->prepare('UPDATE notifications SET is_read=1 WHERE id=? AND company_id=?')->execute([field('notification_id'),$c]);}elseif($a==='approval_decide'){if(!can($db,$user,'approvals.manage'))exit('Forbidden');$id=field('approval_id');$decision=field('decision');if(!in_array($decision,['approved','rejected'],true))return['error'=>'Choose approve or reject.'];$db->beginTransaction();$q=$db->prepare('SELECT * FROM approvals WHERE id=? AND company_id=? FOR UPDATE');$q->execute([$id,$c]);$ap=$q->fetch();if(!$ap||$ap['status']!=='pending')throw new DomainException('This approval has already been decided.');$db->prepare('UPDATE approvals SET status=?,approver_id=?,decision_notes=?,decided_at=NOW() WHERE id=?')->execute([$decision,$user['id'],field('decision_notes'),$id]);if($ap['module_name']==='purchase_request')$db->prepare('UPDATE purchase_requests SET status=?,approved_by=?,approved_at=NOW() WHERE id=? AND company_id=?')->execute([$decision,$user['id'],$ap['record_id'],$c]);if($ap['module_name']==='expense')$db->prepare('UPDATE expenses SET status=?,approved_by=? WHERE id=? AND company_id=?')->execute([$decision,$user['id'],$ap['record_id'],$c]);$db->commit();}else return['error'=>'Unknown action.'];audit($db,$user,'management',$a);$_SESSION['notice']='Updated successfully.';go('./?page='.rawurlencode(field('return_page')?:'management'));}catch(DomainException $e){if($db->inTransaction())$db->rollBack();return['error'=>$e->getMessage()];}catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log($e->getMessage());return['error'=>'The action could not be completed.'];}}
function phase56_export(PDO $db,array $user):never{$type=(string)($_GET['export']??'');if(!can($db,$user,'reports.export')){http_response_code(403);exit('Forbidden');}$c=$user['company_id'];$sets=['projects'=>['Project,Code,Status,Budget,Progress','SELECT name,code,status,budget,progress FROM projects WHERE company_id=?'],'expenses'=>['Date,Project,Category,Amount,Tax,Status','SELECT e.expense_date,p.name,e.category,e.amount,e.tax,e.status FROM expenses e JOIN projects p ON p.id=e.project_id WHERE e.company_id=? ORDER BY e.expense_date DESC'],'leads'=>['Name,Phone,Email,Source,Status,Assigned','SELECT l.name,l.phone,l.email,l.source,l.status,COALESCE(u.name,"") FROM leads l LEFT JOIN users u ON u.id=l.assigned_to WHERE l.company_id=?'],'collections'=>['Customer,Unit,Stage,Due Date,Amount Due,Received,Status','SELECT c.name,u.unit_number,s.stage_name,s.due_date,s.amount_due,s.amount_received,s.status FROM payment_schedules s JOIN bookings b ON b.id=s.booking_id JOIN customers c ON c.id=b.customer_id JOIN units u ON u.id=b.unit_id WHERE s.company_id=?']];if(!isset($sets[$type])){http_response_code(404);exit('Unknown export.');}[$header,$sql]=$sets[$type];$rows=phase_rows($db,$sql,[$c]);header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="'.$type.'-'.date('Y-m-d').'.csv"');$out=fopen('php://output','wb');fputcsv($out,explode(',',$header));foreach($rows as $row)fputcsv($out,array_values($row));fclose($out);exit;}
