<?php
declare(strict_types=1);

function ensure_phase23(PDO $db): void {
    $tables = [
        'materials' => 'CREATE TABLE IF NOT EXISTS materials (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,project_id CHAR(26) NOT NULL,name VARCHAR(160) NOT NULL,category VARCHAR(100) NOT NULL,unit VARCHAR(40) NOT NULL,opening_stock DECIMAL(14,3) NOT NULL DEFAULT 0,minimum_stock DECIMAL(14,3) NOT NULL DEFAULT 0,storage_location VARCHAR(160) NULL,supplier VARCHAR(160) NULL,created_by CHAR(26) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY ix_material_company_project(company_id,project_id),CONSTRAINT fk_mat_company FOREIGN KEY(company_id) REFERENCES companies(id) ON DELETE CASCADE,CONSTRAINT fk_mat_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'material_transactions' => 'CREATE TABLE IF NOT EXISTS material_transactions (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,project_id CHAR(26) NOT NULL,material_id CHAR(26) NOT NULL,transaction_type ENUM("received","issued","returned","wasted","transferred","adjustment") NOT NULL,quantity DECIMAL(14,3) NOT NULL,rate DECIMAL(14,2) NOT NULL DEFAULT 0,notes VARCHAR(255) NULL,transaction_date DATE NOT NULL,created_by CHAR(26) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_mt_material_date(material_id,transaction_date),CONSTRAINT fk_mt_material FOREIGN KEY(material_id) REFERENCES materials(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'material_transfers' => 'CREATE TABLE IF NOT EXISTS material_transfers (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,source_project_id CHAR(26) NOT NULL,destination_project_id CHAR(26) NOT NULL,source_material_id CHAR(26) NOT NULL,destination_material_id CHAR(26) NOT NULL,quantity DECIMAL(14,3) NOT NULL,unit VARCHAR(40) NOT NULL,transfer_date DATE NOT NULL,notes VARCHAR(255) NULL,created_by CHAR(26) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_transfer_company_date(company_id,transfer_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'vendors' => 'CREATE TABLE IF NOT EXISTS vendors (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,name VARCHAR(160) NOT NULL,company_name VARCHAR(160) NULL,phone VARCHAR(30) NULL,email VARCHAR(190) NULL,gst VARCHAR(30) NULL,category VARCHAR(100) NULL,payment_terms VARCHAR(160) NULL,status ENUM("active","inactive") DEFAULT "active",created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_vendor_company(company_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'purchase_requests' => 'CREATE TABLE IF NOT EXISTS purchase_requests (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,project_id CHAR(26) NOT NULL,material_id CHAR(26) NULL,request_number VARCHAR(60) NULL,quantity DECIMAL(14,3) NOT NULL,approved_quantity DECIMAL(14,3) NOT NULL DEFAULT 0,current_quantity DECIMAL(14,3) NOT NULL DEFAULT 0,required_date DATE NULL,priority ENUM("low","normal","high","urgent") DEFAULT "normal",purpose VARCHAR(190) NULL,work_stage VARCHAR(120) NULL,reason VARCHAR(255) NULL,approval_notes VARCHAR(255) NULL,status ENUM("draft","pending","partially_approved","approved","rejected","ordered","partially_received","fulfilled","cancelled") DEFAULT "pending",requested_by CHAR(26) NULL,approved_by CHAR(26) NULL,approved_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_pr_company_status(company_id,status),UNIQUE KEY uq_request_number(company_id,request_number)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'material_request_events' => 'CREATE TABLE IF NOT EXISTS material_request_events (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,request_id CHAR(26) NOT NULL,event_type VARCHAR(60) NOT NULL,status VARCHAR(60) NOT NULL,quantity DECIMAL(14,3) NOT NULL DEFAULT 0,notes VARCHAR(255) NULL,created_by CHAR(26) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_request_event(request_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'purchase_orders' => 'CREATE TABLE IF NOT EXISTS purchase_orders (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,project_id CHAR(26) NOT NULL,purchase_request_id CHAR(26) NULL,vendor_id CHAR(26) NOT NULL,po_number VARCHAR(60) NOT NULL,amount DECIMAL(16,2) NOT NULL DEFAULT 0,expected_delivery DATE NULL,status ENUM("draft","issued","part_received","received","cancelled") DEFAULT "issued",created_by CHAR(26) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_po_company(company_id,po_number)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'labour' => 'CREATE TABLE IF NOT EXISTS labour (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,project_id CHAR(26) NOT NULL,name VARCHAR(160) NOT NULL,phone VARCHAR(30) NULL,labour_type VARCHAR(80) NOT NULL,contractor VARCHAR(160) NULL,daily_rate DECIMAL(12,2) NOT NULL DEFAULT 0,overtime_rate DECIMAL(12,2) NOT NULL DEFAULT 0,joining_date DATE NULL,status ENUM("active","inactive") DEFAULT "active",created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_labour_project(project_id,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'labour_attendance' => 'CREATE TABLE IF NOT EXISTS labour_attendance (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,project_id CHAR(26) NOT NULL,labour_id CHAR(26) NOT NULL,attendance_date DATE NOT NULL,attendance_status ENUM("present","absent","half_day","leave") NOT NULL,overtime_hours DECIMAL(6,2) DEFAULT 0,daily_cost DECIMAL(12,2) DEFAULT 0,created_by CHAR(26) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_attendance(labour_id,attendance_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'site_progress' => 'CREATE TABLE IF NOT EXISTS site_progress (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,project_id CHAR(26) NOT NULL,activity VARCHAR(120) NOT NULL,area_ref VARCHAR(120) NULL,start_date DATE NULL,expected_completion DATE NULL,progress TINYINT UNSIGNED DEFAULT 0,status ENUM("not_started","ongoing","delayed","completed") DEFAULT "not_started",contractor VARCHAR(160) NULL,engineer VARCHAR(160) NULL,notes TEXT NULL,created_by CHAR(26) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY ix_progress_project(project_id,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'expenses' => 'CREATE TABLE IF NOT EXISTS expenses (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,project_id CHAR(26) NOT NULL,category VARCHAR(100) NOT NULL,vendor_id CHAR(26) NULL,amount DECIMAL(16,2) NOT NULL,tax DECIMAL(16,2) NOT NULL DEFAULT 0,expense_date DATE NOT NULL,payment_method VARCHAR(60) NULL,reference_no VARCHAR(100) NULL,description VARCHAR(255) NULL,status ENUM("draft","pending","approved","rejected","paid") DEFAULT "pending",created_by CHAR(26) NULL,approved_by CHAR(26) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_expense_project_date(project_id,expense_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'leads' => 'CREATE TABLE IF NOT EXISTS leads (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,project_id CHAR(26) NULL,name VARCHAR(160) NOT NULL,phone VARCHAR(30) NULL,email VARCHAR(190) NULL,source VARCHAR(100) NULL,campaign VARCHAR(120) NULL,unit_type VARCHAR(60) NULL,budget DECIMAL(16,2) DEFAULT 0,location VARCHAR(160) NULL,status VARCHAR(60) DEFAULT "New",assigned_to CHAR(26) NULL,last_contact_at DATETIME NULL,next_followup_at DATETIME NULL,notes TEXT NULL,created_by CHAR(26) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY ix_lead_company_status(company_id,status),KEY ix_lead_followup(company_id,next_followup_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'lead_calls' => 'CREATE TABLE IF NOT EXISTS lead_calls (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,lead_id CHAR(26) NOT NULL,outcome VARCHAR(60) NOT NULL,notes VARCHAR(255) NULL,next_followup_at DATETIME NULL,called_by CHAR(26) NOT NULL,called_at DATETIME DEFAULT CURRENT_TIMESTAMP,KEY ix_call_lead(lead_id,called_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'followups' => 'CREATE TABLE IF NOT EXISTS followups (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,lead_id CHAR(26) NOT NULL,assigned_user_id CHAR(26) NOT NULL,followup_at DATETIME NOT NULL,type ENUM("call","email","site_visit","meeting") DEFAULT "call",priority ENUM("low","normal","high") DEFAULT "normal",notes VARCHAR(255) NULL,status ENUM("pending","completed","cancelled") DEFAULT "pending",created_by CHAR(26) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_followup_company_date(company_id,followup_at,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'site_visits' => 'CREATE TABLE IF NOT EXISTS site_visits (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,lead_id CHAR(26) NOT NULL,project_id CHAR(26) NOT NULL,assigned_user_id CHAR(26) NOT NULL,visit_at DATETIME NOT NULL,guests SMALLINT DEFAULT 1,unit_interested VARCHAR(80) NULL,budget DECIMAL(16,2) DEFAULT 0,status ENUM("scheduled","completed","cancelled","no_show","rescheduled") DEFAULT "scheduled",notes VARCHAR(255) NULL,outcome VARCHAR(255) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY ix_visit_company_date(company_id,visit_at,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'email_queue' => 'CREATE TABLE IF NOT EXISTS email_queue (id CHAR(26) PRIMARY KEY,company_id CHAR(26) NOT NULL,lead_id CHAR(26) NOT NULL,recipient VARCHAR(190) NOT NULL,subject VARCHAR(190) NOT NULL,body TEXT NOT NULL,status ENUM("queued","sent","failed","cancelled") DEFAULT "queued",provider_error VARCHAR(255) NULL,created_by CHAR(26) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,sent_at DATETIME NULL,KEY ix_email_queue(company_id,status,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4'
    ];
    foreach ($tables as $sql) $db->exec($sql);
    $requestColumns=['request_number VARCHAR(60) NULL','approved_quantity DECIMAL(14,3) NOT NULL DEFAULT 0','current_quantity DECIMAL(14,3) NOT NULL DEFAULT 0','purpose VARCHAR(190) NULL','work_stage VARCHAR(120) NULL','approval_notes VARCHAR(255) NULL'];
    $existingColumns=$db->query('SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME="purchase_requests"')->fetchAll(PDO::FETCH_COLUMN);
    foreach($requestColumns as $definition){$column=strtok($definition,' ');if(!in_array($column,$existingColumns,true))$db->exec('ALTER TABLE purchase_requests ADD COLUMN '.$definition);}
    $db->exec('ALTER TABLE purchase_requests MODIFY status ENUM("draft","pending","partially_approved","approved","rejected","ordered","partially_received","fulfilled","cancelled") DEFAULT "pending"');
    $db->exec('UPDATE purchase_requests SET request_number=CONCAT("MR-",UPPER(LEFT(id,8))) WHERE request_number IS NULL OR request_number=""');
    $collations=$db->query('SELECT TABLE_NAME,TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE()')->fetchAll(PDO::FETCH_KEY_PAIR);
    foreach(array_keys($tables) as $table){if(($collations[$table]??'')!=='utf8mb4_unicode_ci')$db->exec('ALTER TABLE `'.$table.'` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');}
    $permissions=['materials.view','materials.manage','labour.view','labour.manage','progress.view','progress.manage','vendors.view','vendors.manage','purchases.view','purchases.manage','expenses.view','expenses.manage','leads.view','leads.manage','calls.log','emails.queue','followups.manage','visits.manage'];
    foreach($permissions as $key){
        $q=$db->prepare('SELECT id FROM permissions WHERE permission_key=?');$q->execute([$key]);$pid=$q->fetchColumn();
        if(!$pid){$pid=id26();[$module,$action]=explode('.',$key,2);$db->prepare('INSERT INTO permissions(id,module_name,action_name,permission_key) VALUES(?,?,?,?)')->execute([$pid,$module,$action,$key]);}
        $db->prepare('INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT id,? FROM roles WHERE code="OWNER"')->execute([$pid]);
    }
}

function scoped_project(PDO $db,array $user,string $projectId): bool {
    $q=$db->prepare('SELECT 1 FROM projects p WHERE p.id=? AND p.company_id=? AND (EXISTS(SELECT 1 FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=? AND r.company_id=p.company_id AND r.code IN("OWNER","OPERATIONS_HEAD")) OR EXISTS(SELECT 1 FROM user_projects up WHERE up.user_id=? AND up.project_id=p.id))');$q->execute([$projectId,$user['company_id'],$user['id'],$user['id']]);return(bool)$q->fetchColumn();
}
function phase23_action(PDO $db,array $user): ?array {
    $a=(string)($_POST['phase_action']??''); if($a==='')return null;
    $company=$user['company_id'];$page=(string)($_POST['return_page']??'construction');
    $project=trim((string)($_POST['project_id']??''));
    if($project!==''&&!scoped_project($db,$user,$project))return ['error'=>'Choose a valid project.'];
    $need=function(string $permission)use($db,$user,$project){if(!can($db,$user,$permission,$project?:null)){http_response_code(403);exit('Forbidden');}};
    try{
        if($a==='material_add'){$need('materials.manage');$db->prepare('INSERT INTO materials(id,company_id,project_id,name,category,unit,opening_stock,minimum_stock,storage_location,supplier,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([id26(),$company,$project,field('name'),field('category'),field('unit'),(float)($_POST['opening_stock']??0),(float)($_POST['minimum_stock']??0),field('storage_location'),field('supplier'),$user['id']]);}
        elseif($a==='material_tx'){$need('materials.manage');$mid=field('material_id');$q=$db->prepare('SELECT 1 FROM materials WHERE id=? AND company_id=? AND project_id=?');$q->execute([$mid,$company,$project]);if(!$q->fetchColumn())throw new RuntimeException('material');$type=field('transaction_type');if(!in_array($type,['received','issued','returned','wasted','transferred','adjustment'],true))throw new RuntimeException('type');$db->prepare('INSERT INTO material_transactions(id,company_id,project_id,material_id,transaction_type,quantity,rate,notes,transaction_date,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([id26(),$company,$project,$mid,$type,max(0,(float)($_POST['quantity']??0)),max(0,(float)($_POST['rate']??0)),field('notes'),field('transaction_date')?:date('Y-m-d'),$user['id']]);}
        elseif($a==='material_transfer'){$need('materials.manage');$sourceMaterialId=field('material_id');$destinationProjectId=field('destination_project_id');$quantity=max(0,(float)($_POST['quantity']??0));if($destinationProjectId===$project||!scoped_project($db,$user,$destinationProjectId)||$quantity<=0)throw new RuntimeException('transfer');$db->beginTransaction();$stockQuery=$db->prepare('SELECT m.*,m.opening_stock+COALESCE(SUM(CASE WHEN t.transaction_type IN("received","returned","adjustment") THEN t.quantity WHEN t.transaction_type IN("issued","wasted","transferred") THEN -t.quantity ELSE 0 END),0) current_stock FROM materials m LEFT JOIN material_transactions t ON t.material_id=m.id WHERE m.id=? AND m.company_id=? AND m.project_id=? GROUP BY m.id FOR UPDATE');$stockQuery->execute([$sourceMaterialId,$company,$project]);$source=$stockQuery->fetch();if(!$source||$quantity>max(0,(float)$source['current_stock']-(float)$source['minimum_stock']))throw new RuntimeException('excess');$destinationQuery=$db->prepare('SELECT id FROM materials WHERE company_id=? AND project_id=? AND LOWER(name)=LOWER(?) AND unit=? LIMIT 1');$destinationQuery->execute([$company,$destinationProjectId,$source['name'],$source['unit']]);$destinationMaterialId=$destinationQuery->fetchColumn();if(!$destinationMaterialId){$destinationMaterialId=id26();$db->prepare('INSERT INTO materials(id,company_id,project_id,name,category,unit,opening_stock,minimum_stock,storage_location,supplier,created_by) VALUES(?,?,?,?,?,?,0,0,?,?,?)')->execute([$destinationMaterialId,$company,$destinationProjectId,$source['name'],$source['category'],$source['unit'],$source['storage_location'],$source['supplier'],$user['id']]);}$date=field('transaction_date')?:date('Y-m-d');$notes=field('notes');$db->prepare('INSERT INTO material_transactions(id,company_id,project_id,material_id,transaction_type,quantity,rate,notes,transaction_date,created_by) VALUES(?,?,?,?,"transferred",?,0,?,?,?)')->execute([id26(),$company,$project,$sourceMaterialId,$quantity,$notes,$date,$user['id']]);$db->prepare('INSERT INTO material_transactions(id,company_id,project_id,material_id,transaction_type,quantity,rate,notes,transaction_date,created_by) VALUES(?,?,?,?,"received",?,0,?,?,?)')->execute([id26(),$company,$destinationProjectId,$destinationMaterialId,$quantity,'Transferred from another site'.($notes?' · '.$notes:''),$date,$user['id']]);$db->prepare('INSERT INTO material_transfers(id,company_id,source_project_id,destination_project_id,source_material_id,destination_material_id,quantity,unit,transfer_date,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([id26(),$company,$project,$destinationProjectId,$sourceMaterialId,$destinationMaterialId,$quantity,$source['unit'],$date,$notes,$user['id']]);$db->commit();}
        elseif($a==='vendor_add'){$need('vendors.manage');$db->prepare('INSERT INTO vendors(id,company_id,name,company_name,phone,email,gst,category,payment_terms) VALUES(?,?,?,?,?,?,?,?,?)')->execute([id26(),$company,field('name'),field('company_name'),field('phone'),field('email'),field('gst'),field('category'),field('payment_terms')]);}
        elseif($a==='purchase_request'){$need('purchases.manage');$materialId=field('material_id')?:null;$quantity=max(0,(float)($_POST['quantity']??0));if(!$materialId||$quantity<=0)throw new DomainException('Choose a material and enter the required quantity.');$stock=$db->prepare('SELECT opening_stock+COALESCE(SUM(CASE WHEN t.transaction_type IN("received","returned","adjustment") THEN t.quantity WHEN t.transaction_type IN("issued","wasted","transferred") THEN -t.quantity ELSE 0 END),0) balance FROM materials m LEFT JOIN material_transactions t ON t.material_id=m.id WHERE m.id=? AND m.company_id=? AND m.project_id=? GROUP BY m.id');$stock->execute([$materialId,$company,$project]);$current=(float)($stock->fetchColumn()?:0);$id=id26();$requestNumber='MR-'.date('ymd').'-'.strtoupper(substr(bin2hex(random_bytes(3)),0,6));$db->beginTransaction();$db->prepare('INSERT INTO purchase_requests(id,company_id,project_id,material_id,request_number,quantity,current_quantity,required_date,priority,purpose,work_stage,reason,requested_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$id,$company,$project,$materialId,$requestNumber,$quantity,$current,field('required_date')?:null,field('priority'),field('purpose'),field('work_stage'),field('reason'),$user['id']]);$db->prepare('INSERT INTO material_request_events(id,company_id,request_id,event_type,status,quantity,notes,created_by) VALUES(?,?,?,?,?,?,?,?)')->execute([id26(),$company,$id,'created','pending',$quantity,field('reason'),$user['id']]);$db->commit();}
        elseif($a==='purchase_status'){$need('approvals.manage');$id=field('record_id');$status=field('status');if(!in_array($status,['approved','partially_approved','rejected','cancelled'],true))throw new DomainException('Choose a valid approval decision.');$db->beginTransaction();$q=$db->prepare('SELECT quantity,status FROM purchase_requests WHERE id=? AND company_id=? AND project_id=? FOR UPDATE');$q->execute([$id,$company,$project]);$request=$q->fetch();if(!$request||!in_array($request['status'],['pending','partially_approved'],true))throw new DomainException('This request is no longer awaiting approval.');$approved=$status==='approved'?(float)$request['quantity']:($status==='partially_approved'?max(0,min((float)$request['quantity'],(float)($_POST['approved_quantity']??0))):0);if($status==='partially_approved'&&$approved<=0)throw new DomainException('Enter the quantity being partially approved.');$db->prepare('UPDATE purchase_requests SET status=?,approved_quantity=?,approval_notes=?,approved_by=?,approved_at=NOW() WHERE id=? AND company_id=?')->execute([$status,$approved,field('approval_notes'),$user['id'],$id,$company]);$db->prepare('INSERT INTO material_request_events(id,company_id,request_id,event_type,status,quantity,notes,created_by) VALUES(?,?,?,?,?,?,?,?)')->execute([id26(),$company,$id,'approval',$status,$approved,field('approval_notes'),$user['id']]);$db->commit();}
        elseif($a==='purchase_order'){$need('purchases.manage');$db->prepare('INSERT INTO purchase_orders(id,company_id,project_id,purchase_request_id,vendor_id,po_number,amount,expected_delivery,created_by) VALUES(?,?,?,?,?,?,?,?,?)')->execute([id26(),$company,$project,field('purchase_request_id')?:null,field('vendor_id'),strtoupper(field('po_number')),max(0,(float)($_POST['amount']??0)),field('expected_delivery')?:null,$user['id']]);}
        elseif($a==='labour_add'){$need('labour.manage');$db->prepare('INSERT INTO labour(id,company_id,project_id,name,phone,labour_type,contractor,daily_rate,overtime_rate,joining_date) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([id26(),$company,$project,field('name'),field('phone'),field('labour_type'),field('contractor'),max(0,(float)($_POST['daily_rate']??0)),max(0,(float)($_POST['overtime_rate']??0)),field('joining_date')?:null]);}
        elseif($a==='attendance_add'){$need('labour.manage');$lid=field('labour_id');$q=$db->prepare('SELECT daily_rate,overtime_rate FROM labour WHERE id=? AND company_id=? AND project_id=?');$q->execute([$lid,$company,$project]);$worker=$q->fetch();if(!$worker)throw new RuntimeException('labour');$status=field('attendance_status');$factor=$status==='present'?1:($status==='half_day'?.5:0);$ot=max(0,(float)($_POST['overtime_hours']??0));$cost=$factor*(float)$worker['daily_rate']+$ot*(float)$worker['overtime_rate'];$db->prepare('INSERT INTO labour_attendance(id,company_id,project_id,labour_id,attendance_date,attendance_status,overtime_hours,daily_cost,created_by) VALUES(?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE attendance_status=VALUES(attendance_status),overtime_hours=VALUES(overtime_hours),daily_cost=VALUES(daily_cost)')->execute([id26(),$company,$project,$lid,field('attendance_date')?:date('Y-m-d'),$status,$ot,$cost,$user['id']]);}
        elseif($a==='progress_add'){$need('progress.manage');$db->prepare('INSERT INTO site_progress(id,company_id,project_id,activity,area_ref,start_date,expected_completion,progress,status,contractor,engineer,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([id26(),$company,$project,field('activity'),field('area_ref'),field('start_date')?:null,field('expected_completion')?:null,min(100,max(0,(int)($_POST['progress']??0))),field('status'),field('contractor'),field('engineer'),field('notes'),$user['id']]);}
        elseif($a==='expense_add'){$need('expenses.manage');$db->prepare('INSERT INTO expenses(id,company_id,project_id,category,vendor_id,amount,tax,expense_date,payment_method,reference_no,description,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([id26(),$company,$project,field('category'),field('vendor_id')?:null,max(0,(float)($_POST['amount']??0)),max(0,(float)($_POST['tax']??0)),field('expense_date')?:date('Y-m-d'),field('payment_method'),field('reference_no'),field('description'),field('status'),$user['id']]);}
        elseif($a==='lead_import'){$need('leads.manage');$file=$_FILES['lead_file']??null;if(!$file||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||($file['size']??0)>2097152)return ['error'=>'Choose a CSV file smaller than 2 MB.'];if(strtolower(pathinfo((string)$file['name'],PATHINFO_EXTENSION))!=='csv')return ['error'=>'Only CSV lead files are accepted.'];$h=fopen((string)$file['tmp_name'],'rb');$header=$h?fgetcsv($h):false;if(!$header){if($h)fclose($h);return ['error'=>'The CSV has no header row.'];}$header=array_map(fn($x)=>strtolower(trim((string)$x)),$header);$inserted=0;$skipped=0;$check=$db->prepare('SELECT 1 FROM leads WHERE company_id=? AND ((phone<>"" AND phone=?) OR (email<>"" AND email=?))');$add=$db->prepare('INSERT INTO leads(id,company_id,project_id,name,phone,email,source,campaign,unit_type,budget,location,status,assigned_to,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');while(($row=fgetcsv($h))!==false){$r=array_combine($header,array_pad($row,count($header),''));$name=trim((string)($r['name']??''));$phone=trim((string)($r['phone']??''));$email=strtolower(trim((string)($r['email']??'')));if($name===''||($phone===''&&$email==='')){$skipped++;continue;}$check->execute([$company,$phone,$email]);if($check->fetchColumn()){$skipped++;continue;}$add->execute([id26(),$company,$project?:null,$name,$phone,$email,trim((string)($r['source']??'')),trim((string)($r['campaign']??'')),trim((string)($r['unit type']??$r['unit_type']??'')),max(0,(float)($r['budget']??0)),trim((string)($r['location']??'')),'New',field('assigned_to')?:null,trim((string)($r['notes']??'')),$user['id']]);$inserted++;}fclose($h);$_SESSION['notice']=$inserted.' leads imported; '.$skipped.' skipped as duplicates or invalid.';go('./?page=leads');}
        elseif($a==='lead_add'){$need('leads.manage');$phone=field('phone');$email=strtolower(field('email'));$q=$db->prepare('SELECT 1 FROM leads WHERE company_id=? AND ((phone<>"" AND phone=?) OR (email<>"" AND email=?))');$q->execute([$company,$phone,$email]);if($q->fetchColumn())return ['error'=>'A lead with this phone number or email already exists.'];$db->prepare('INSERT INTO leads(id,company_id,project_id,name,phone,email,source,campaign,unit_type,budget,location,status,assigned_to,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([id26(),$company,$project?:null,field('name'),$phone,$email,field('source'),field('campaign'),field('unit_type'),max(0,(float)($_POST['budget']??0)),field('location'),field('status')?:'New',field('assigned_to')?:null,field('notes'),$user['id']]);}
        elseif($a==='lead_update'){$need('leads.manage');$db->prepare('UPDATE leads SET status=?,assigned_to=?,next_followup_at=? WHERE id=? AND company_id=?')->execute([field('status'),field('assigned_to')?:null,field('next_followup_at')?:null,field('lead_id'),$company]);}
        elseif($a==='call_log'){$need('calls.log');$lead=field('lead_id');$db->prepare('INSERT INTO lead_calls(id,company_id,lead_id,outcome,notes,next_followup_at,called_by) SELECT ?,?,?,?,?,?,? FROM leads WHERE id=? AND company_id=?')->execute([id26(),$company,$lead,field('outcome'),field('notes'),field('next_followup_at')?:null,$user['id'],$lead,$company]);$db->prepare('UPDATE leads SET last_contact_at=NOW(),next_followup_at=? WHERE id=? AND company_id=?')->execute([field('next_followup_at')?:null,$lead,$company]);}
        elseif($a==='followup_add'){$need('followups.manage');$db->prepare('INSERT INTO followups(id,company_id,lead_id,assigned_user_id,followup_at,type,priority,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?)')->execute([id26(),$company,field('lead_id'),field('assigned_user_id'),field('followup_at'),field('type'),field('priority'),field('notes'),$user['id']]);}
        elseif($a==='visit_add'){$need('visits.manage');$db->prepare('INSERT INTO site_visits(id,company_id,lead_id,project_id,assigned_user_id,visit_at,guests,unit_interested,budget,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([id26(),$company,field('lead_id'),$project,field('assigned_user_id'),field('visit_at'),max(1,(int)($_POST['guests']??1)),field('unit_interested'),max(0,(float)($_POST['budget']??0)),field('status'),field('notes')]);}
        elseif($a==='email_queue'){$need('emails.queue');$lead=field('lead_id');$q=$db->prepare('SELECT email,name FROM leads WHERE id=? AND company_id=?');$q->execute([$lead,$company]);$l=$q->fetch();if(!$l||!filter_var($l['email'],FILTER_VALIDATE_EMAIL))return ['error'=>'This lead does not have a valid email address.'];$db->prepare('INSERT INTO email_queue(id,company_id,lead_id,recipient,subject,body,created_by) VALUES(?,?,?,?,?,?,?)')->execute([id26(),$company,$lead,$l['email'],field('subject'),field('body'),$user['id']]);}
        else return ['error'=>'Unknown action.'];
        audit($db,$user,strtok($a,'_'),'create');$_SESSION['notice']='Saved successfully.';go('./?page='.rawurlencode($page));
    }catch(DomainException $e){if($db->inTransaction())$db->rollBack();return ['error'=>$e->getMessage()];}catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log($e->getMessage());return ['error'=>$e->getMessage()==='excess'?'Transfer quantity cannot exceed available excess stock.':'The record could not be saved. Check the required fields and try again.'];}
}

function phase_rows(PDO $db,string $sql,array $params): array {$q=$db->prepare($sql);$q->execute($params);return$q->fetchAll();}
function phase_one(PDO $db,string $sql,array $params): array {$q=$db->prepare($sql);$q->execute($params);return$q->fetch()?:[];}
function phase_hidden(string $action,string $page,string $project): string {return '<input type="hidden" name="csrf" value="'.e($_SESSION['csrf']).'"><input type="hidden" name="phase_action" value="'.e($action).'"><input type="hidden" name="return_page" value="'.e($page).'"><input type="hidden" name="project_id" value="'.e($project).'">';}
function inr(mixed $n): string{return '₹'.number_format((float)$n);}
function phase_table(array $heads,array $rows): string {$h='<section class="table-card"><table><thead><tr>';foreach($heads as $x)$h.='<th>'.e($x).'</th>';$h.='</tr></thead><tbody>';if(!$rows)$h.='<tr><td colspan="'.count($heads).'" class="empty-cell">No records yet.</td></tr>';foreach($rows as $r){$h.='<tr>';foreach($r as $x)$h.='<td>'.$x.'</td>';$h.='</tr>';}$h.='</tbody></table></section>';return$h;}
