<?php
declare(strict_types=1);
$cid=$user['company_id'];
$selectedProject=(string)($_GET['project']??($projects[0]['id']??''));
if($selectedProject&&!scoped_project($db,$user,$selectedProject))$selectedProject=(string)($projects[0]['id']??'');
$materials=phase_rows($db,'SELECT m.*,m.opening_stock+COALESCE(SUM(CASE WHEN t.transaction_type IN("received","returned","adjustment") THEN t.quantity WHEN t.transaction_type IN("issued","wasted","transferred") THEN -t.quantity ELSE 0 END),0) current_stock FROM materials m LEFT JOIN material_transactions t ON t.material_id=m.id WHERE m.company_id=? AND m.project_id=? GROUP BY m.id ORDER BY m.name',[$cid,$selectedProject]);
$requests=phase_rows($db,'SELECT pr.*,m.name material_name,m.unit,u.name requester,ap.name approver FROM purchase_requests pr JOIN materials m ON m.id=pr.material_id LEFT JOIN users u ON u.id=pr.requested_by LEFT JOIN users ap ON ap.id=pr.approved_by WHERE pr.company_id=? AND pr.project_id=? ORDER BY pr.created_at DESC',[$cid,$selectedProject]);
$vendors=phase_rows($db,'SELECT * FROM vendors WHERE company_id=? AND status="active" ORDER BY name',[$cid]);
$orders=phase_rows($db,'SELECT po.*,v.name vendor_name,pr.request_number FROM purchase_orders po JOIN vendors v ON v.id=po.vendor_id LEFT JOIN purchase_requests pr ON pr.id=po.purchase_request_id WHERE po.company_id=? AND po.project_id=? ORDER BY po.created_at DESC',[$cid,$selectedProject]);
$excess=phase_rows($db,'SELECT m.name,m.unit,p.name site_name,m.opening_stock+COALESCE(SUM(CASE WHEN t.transaction_type IN("received","returned","adjustment") THEN t.quantity WHEN t.transaction_type IN("issued","wasted","transferred") THEN -t.quantity ELSE 0 END),0)-m.minimum_stock excess_qty FROM materials m JOIN projects p ON p.id=m.project_id LEFT JOIN material_transactions t ON t.material_id=m.id WHERE m.company_id=? AND m.project_id<>? GROUP BY m.id HAVING excess_qty>0 ORDER BY m.name,p.name',[$cid,$selectedProject]);
?>
<section class="page-title inventory-title"><div><span class="eyebrow">REQUIRE → CHECK STOCK → APPROVE → ORDER</span><h1>Material Requests & Purchases</h1><p class="muted">Check stock and excess at other sites before purchasing new material.</p></div><form method="get" class="project-filter"><input type="hidden" name="page" value="purchases"><select name="project" onchange="this.form.submit()"><?php foreach($projects as $p):?><option value="<?=e($p['id'])?>" <?=$p['id']===$selectedProject?'selected':''?>><?=e($p['name'])?></option><?php endforeach;?></select></form></section>
<?php if(!$selectedProject):?><p class="empty-state">Add or assign a construction site before creating a material request.</p><?php else:?>
<div class="split"><form class="form-card" method="post"><h2>Create material request</h2><p class="muted">Every request receives a unique number and records the current site balance.</p><?=phase_hidden('purchase_request','purchases',$selectedProject)?><label class="field">Material<select name="material_id" required><option value="">Select material</option><?php foreach($materials as $m):?><option value="<?=e($m['id'])?>"><?=e($m['name'].' · '.$m['current_stock'].' '.$m['unit'].' available')?></option><?php endforeach;?></select></label><div class="form-grid"><label class="field">Required quantity<input type="number" min=".001" step=".001" name="quantity" required></label><label class="field">Required by<input type="date" name="required_date" required></label></div><div class="form-grid"><label class="field">Priority<select name="priority"><option>normal</option><option>high</option><option>urgent</option><option>low</option></select></label><label class="field">Work stage<input name="work_stage" placeholder="Foundation, slab, finishing" required></label></div><label class="field">Purpose<input name="purpose" placeholder="Where or why this material is needed" required></label><label class="field">Notes<input name="reason"></label><button class="button">Submit for approval</button></form>
<section class="form-card"><h2>Excess available at other sites</h2><p class="muted">Use a site transfer before creating a purchase order when suitable stock exists.</p><?php foreach(array_slice($excess,0,12) as $x):?><div class="stock-alert excess"><div><b><?=e($x['name'])?></b><small><?=e($x['site_name'])?></small></div><strong><?=e(number_format((float)$x['excess_qty'],3).' '.$x['unit'])?></strong></div><?php endforeach;?><?php if(!$excess):?><p class="empty-cell">No transferable excess is currently available.</p><?php endif;?><a class="button" href="?page=transfers">Open transfers</a></section></div>
<section class="panel"><div class="panel-head"><div><h2>Material requests</h2><p class="muted">Partial approval is supported and every decision is recorded.</p></div></div><?=phase_table(['Request','Material','Required','Available then','Required by','Purpose / stage','Status','Decision'],array_map(function($r)use($selectedProject,$db,$user){$decision='';if(in_array($r['status'],['pending','partially_approved'],true)&&can($db,$user,'approvals.manage',$selectedProject))$decision='<form method="post" class="inline-form">'.phase_hidden('purchase_status','purchases',$selectedProject).'<input type="hidden" name="record_id" value="'.e($r['id']).'"><input type="number" min=".001" step=".001" max="'.e($r['quantity']).'" name="approved_quantity" placeholder="Partial qty"><input name="approval_notes" placeholder="Decision note"><button name="status" value="approved">Approve all</button><button name="status" value="partially_approved">Approve partial</button><button class="danger" name="status" value="rejected">Reject</button></form>';return[e($r['request_number']),e($r['material_name']),e($r['quantity'].' '.$r['unit']),e($r['current_quantity'].' '.$r['unit']),e($r['required_date']),e(($r['purpose']?:'—').' · '.($r['work_stage']?:'—')), '<span class="pill">'.e(str_replace('_',' ',$r['status'])).'</span><small>'.e($r['approved_quantity']?'Approved: '.$r['approved_quantity']:'').'</small>',$decision];},$requests))?></section>
<div class="split"><form class="form-card" method="post"><h2>Create purchase order</h2><p class="muted">Only approved material requests should be ordered.</p><?=phase_hidden('purchase_order','purchases',$selectedProject)?><label class="field">Approved request<select name="purchase_request_id" required><option value="">Select approved request</option><?php foreach(array_filter($requests,fn($r)=>in_array($r['status'],['approved','partially_approved'],true)) as $r):?><option value="<?=e($r['id'])?>"><?=e($r['request_number'].' · '.$r['material_name'])?></option><?php endforeach;?></select></label><label class="field">Vendor<select name="vendor_id" required><?php foreach($vendors as $v):?><option value="<?=e($v['id'])?>"><?=e($v['name'])?></option><?php endforeach;?></select></label><div class="form-grid"><label class="field">PO number<input name="po_number" required></label><label class="field">Amount<input type="number" min="0" step=".01" name="amount" required></label></div><label class="field">Expected delivery<input type="date" name="expected_delivery" required></label><button class="button">Issue purchase order</button></form><section class="form-card"><h2>Purchase orders</h2><?=phase_table(['PO','Request','Vendor','Amount','Expected','Status'],array_map(fn($o)=>[e($o['po_number']),e($o['request_number']?:'—'),e($o['vendor_name']),inr($o['amount']),e($o['expected_delivery']),'<span class="pill">'.e(str_replace('_',' ',$o['status'])).'</span>'],$orders))?></section></div>
<?php endif;?>
